const oldCornerComms = {
    "BDL-BDR" : "[U': [R', U' L U]]",
    "BDL-DBR" : "[U R: [D2, R U' R']]",
    "BDL-DFL" : "[x': [D2, R U2 R']]",
    "BDL-DFR" : "[U' D' R': [R' D R, U]]",
    "BDR-DBL" : "[R U' D' : [D2, R' U R]]",
    "BDR-DFL" : "[D' R: [R D' R', U']]",
    "BDR-DFR" : "[D' R D: [U, R' D' R]]",
    "BUL-BDL" : "[U' R' U': [R D' R', U']]",
    "BUL-BDR" : "[R2 U : [R D R', U2]]",
    "BUL-DBL" : "[U' D R': [R' D R, U']]",
    "BUL-DBR" : "[U R : [D', R U' R']]",
    "BUL-DFL" : "[U' R': [R' D R, U']]",
    "BUL-DFR" : "[U' D' R': [R' D R, U']]",
    "BUR-BDL" : "[R' U: [D2, R U' R']]",
    "BUR-BDR" : "[R U': [R' U R, D]]",
    "BUR-BUL" : "[R, U' L' U]",
    "BUR-DBL" : "[R U': [R' U R, D']] ",
    "BUR-DBR" : "[D R U': [R' U R, D']]",
    "BUR-DFL" : "[U D R' U': [R U R', D']]",
    "BUR-DFR" : "[U R' U': [R U R', D']]",
    "DBR-DBL" : "[z: [R U2 R', D2]]",
    "DFL-DBL" : "[x U: [R' D R, U2]]",
    "DFL-DBR" : "[U' R2: [R2 U R2 U' R2, D]]",
    "DFL-DFR" : "[U' R' F' : [R U' R', D']]",
    "DFR-DBL" : "[R U' R' U: [R D' R', U2]]",
    "DFR-DBR" : "[F' R U': [R' D' R, U2]]",
    "FDL-BDL" : "[D' R D': [R' U' R, D2]]",
    "FDL-BDR" : "[D: [R U R', D2]]",
    "FDL-BUL" : "[D x': [R U' R', D']]",
    "FDL-BUR" : "[R', U L' U']",
    "FDL-DBL" : "[Lw' D: [R' D' R, U']]",
    "FDL-DBR" : "[D R: [R D' R', U']]",
    "FDL-DFR" : "[R U' R': [R' D R, U2]]",
    "FDL-RDB" : "[R D: [D, R' U' R]]",
    "FDL-RDF" : "[D, R U R']",
    "FDL-RUB" : "[F' U: [R' D' R, U2]]",
    "FDR-BDL" : "[U: [R U' R', D2]]",
    "FDR-BDR" : "[D R D: [R' U' R, D2]]",
    "FDR-BUL" : "[R: [U' L' U, R]]",
    "FDR-BUR" : "[D' R' U: [R U' R', D]]",
    "FDR-DBL" : "[z: [R U2 R', D]]",
    "FDR-DBR" : "[U R D': [U', R' D R]]",
    "FDR-DFL" : "[R : [R' U R U', F2]]",
    "FDR-FDL" : "[U L' U', R]",
    "FDR-RDB" : "[U: [R U' R', D']]",
    "FDR-RUB" : "[U' R' U: [R D R', U2]]",
    "FUL-BDL" : "[D R' D : [F2, D' R D R']]",
    "FUL-BDR" : "[R U: [R' D' R, U2]]",
    "FUL-BUL" : "[R U R' D': [U2, R' D R]]",
    "FUL-BUR" : "[R D' U: [R' D' R, U2]]",
    "FUL-DBL" : "[R: [R D' R', U2]]",
    "FUL-DBR" : "[D R: [R D' R', U2]]",
    "FUL-DFL" : "[R U D: [R' D' R, U2]]",
    "FUL-DFR" : "[D' R U D: [R' D' R, U2]]",
    "FUL-FDL" : "[R U: [R' D R, U2]]",
    "FUL-FDR" : "[R': [R D' R' D, F2]]",
    "FUL-RDB" : "[Lw' U': [R D R', U2]]",
    "FUL-RDF" : "[Lw': [R' D' R, U2]]",
    "FUL-RUB" : "[R' : [U', R2 D' R2 D R2]]",
    "LDF-BDL" : "[U D: [R U' R', D]]",
    "LDF-BDR" : "[R' U' R: [U2, R' D R]]",
    "LDF-BUL" : "[Lw U2: [R D' R', U]]",
    "LDF-BUR" : "[R' U: [R U' R', D]]",
    "LDF-DBL" : "[F': [R U' R', D2]]",
    "LDF-DBR" : "[U R : [D, R U' R']]",
    "LDF-DFR" : "[U D R D' : [U', R' D R]]",
    "LDF-FDR" : "[U: [D, R U' R']]",
    "LDF-FUL" : "[D R': [F2, R D' R' D]]",
    "LDF-LFB" : "[z': [R U' R', D']]",
    "LDF-RDB" : "[D U: [R U' R', D2]]",
    "LDF-RDF" : "[U R' D: [R U' R', D2]]",
    "LDF-RUB" : "[U R U: [R' D R, U2]]",
    "LFB-BDR" : "[D': [D', R U R']]",
    "LFB-BUL" : "[U2 R: [R D' R', U]]",
    "LFB-BUR" : "[U' L U, R]",
    "LFB-DBR" : "[R D' R': [R' D R, U]]",
    "LFB-DFL" : "[R D R' D: [R U R', D2]]",
    "LFB-DFR" : "[D2 R: [R D' R', U']]",
    "LFB-FDL" : "[D2: [R U R', D']]",
    "LFB-FDR" : "[U R U': [R D' R', U']]",
    "LFB-FUL" : "[Lw': [U2, R' D R]]",
    "LFB-RDB" : "[R D': [R' U' R, D2]]",
    "LFB-RDF" : "[D2, R U R']",
    "LFB-RUB" : "[U R: [R D' R', U2]]",
    "LUB-BDL" : "[U R': [U', R' D2 R]]",
    "LUB-BDR" : "[R U: [R' D' R, U]]",
    "LUB-BUR" : "[U R': [U', R' D' R]]",
    "LUB-DBL" : "[R: [R D' R', U]]",
    "LUB-DBR" : "[D R: [R D' R', U]]",
    "LUB-DFL" : "[R: [R D2 R', U]]",
    "LUB-DFR" : "[D2 R: [R D' R', U]]",
    "LUB-FDL" : "[R U: [R' D R, U]]",
    "LUB-FDR" : "[R U R' : [R' D' R, U']]",
    "LUB-FUL" : "[Lw' U: [R D' R', U2]]",
    "LUB-LDF" : "[U R' U': [R' D R, U]]",
    "LUB-LFB" : "[R D': [R D R', U]]",
    "LUB-LUF" : "[L, U' R' U]",
    "LUB-RDB" : "[R D: [R D R', U]]",
    "LUB-RDF" : "[D' R U : [R' D R, U]]",
    "LUB-RUB" : "[R: [R2' D R2 D' R2', U]]",
    "LUF-BDL" : "[x': [R U2 R', D]]",
    "LUF-BDR" : "[F: [D', R U R']]",
    "LUF-BUL" : "[x': [R U' R', D]]",
    "LUF-BUR" : "[R', U L U']",
    "LUF-DBL" : "[R2 D2: [R U' R', D]]",
    "LUF-DBR" : "[z: [D2, R U R']]",
    "LUF-DFL" : "[U' R' U: [R U' R', D]]",
    "LUF-DFR" : "[R U' R': [R' D' R, U2]]",
    "LUF-FDL" : "[D R' U': [D', R U R']]",
    "LUF-FDR" : "[R, U L U']",
    "LUF-LDF" : "[R' U' : [D, R U R']]",
    "LUF-LFB" : "[z: [R' D' R, U2]]",
    "LUF-RDB" : "[R' U': [R' D' R, U2]]",
    "LUF-RDF" : "[R' U': [D', R U R']]",
    "LUF-RUB" : "[F' U: [R' D R, U2]]",
    "RDB-BDL" : "[U': [R' U' R, D']]",
    "RDB-BUL" : "[R' U: [R' D' R, U]]",
    "RDB-BUR" : "[U' R U: [R' U' R, D]]",
    "RDB-DBL" : "[R2 D2: [R U R', D]]",
    "RDB-DFL" : "[U' R': [R' D R, U]]",
    "RDB-DFR" : "[R U' D' R' : [R' D R, U2]]",
    "RDB-RDF" : "[R D': [R' D R, U]]",
    "RDF-BDL" : "[x': [R U2 R', D']]",
    "RDF-BDR" : "[R U R', D']",
    "RDF-BUL" : "[x': [R U' R', D']]",
    "RDF-BUR" : "[R D: [R D' R', U']]",
    "RDF-DBL" : "[R: [R D' R', U']]",
    "RDF-DBR" : "[R U' R' D R: [U, R D' R']]",
    "RDF-DFL" : "[R D: [U, R' D' R]]",
    "RUB-BDL" : "[U' R' U': [R D' R', U2]]",
    "RUB-BDR" : "[U D R: [U2, R D' R']]",
    "RUB-BUL" : "[U R: [U2, R D R']]",
    "RUB-DBL" : "[U' D R': [R' D R, U2]]",
    "RUB-DBR" : "[F': [U2, R D R']]",
    "RUB-DFL" : "[U' R': [R' D R, U2]]",
    "RUB-DFR" : "[U' D' R': [R' D R, U2]]",
    "RUB-RDB" : "[U R U': [R' D' R, U2]]",
    "RUB-RDF" : "[U' R' U' D: [R D' R', U2]]",
    "UBL-BDL" : "[R' D2 R, U2]",
    "UBL-BDR" : "[U' D: [R D' R', U2]]",
    "UBL-BUR" : "[R' D': [U2, R' D R]]",
    "UBL-DBL" : "[D' R D' R': [R' D R, U2]]",
    "UBL-DBR" : "[R D' R': [R' D R, U2]]",
    "UBL-DFL" : "[R F' R' U': [R D R', U2]]",
    "UBL-DFR" : "[D R D' R': [R' D R, U2]]",
    "UBL-FDL" : "[U' D': [R D' R', U2]]",
    "UBL-FDR" : "[D U': [R D R', U2]]",
    "UBL-FUL" : "[Lw': [U2, R' D2 R]]",
    "UBL-LDF" : "[R' D R, U2]",
    "UBL-LFB" : "[U': [R D' R', U2]]",
    "UBL-LUF" : "[F: [U2, R' D' R]]",
    "UBL-RDB" : "[U': [R D R', U2]]",
    "UBL-RDF" : "[R' D' R, U2]",
    "UBL-RUB" : "[R D R': [R' D2 R, U2]]",
    "UBR-BDL" : "[R' D2 R, U]",
    "UBR-BDR" : "[D: [U', R D' R']]",
    "UBR-BUL" : "[R': [R' D' R, U2]]",
    "UBR-DBL" : "[x: [R' U' R, D2]]",
    "UBR-DBR" : "[U R D' R': [U', R' D R]]",
    "UBR-DFL" : "[x': [D2, R U R']]",
    "UBR-DFR" : "[U' R' D R: [R D' R', U]]",
    "UBR-FDL" : "[D: [R' D' R, U]]",
    "UBR-FDR" : "[D': [R' D R, U]]",
    "UBR-FUL" : "[R: [U2, R D R']]",
    "UBR-LDF" : "[R' D R, U]",
    "UBR-LFB" : "[U', R D' R']",
    "UBR-LUB" : "[R: [U, R D R']]",
    "UBR-LUF" : "[R': [R' D' R, U']]",
    "UBR-RDB" : "[U', R D R']",
    "UBR-RDF" : "[R' D' R, U]",
    "UBR-UBL" : "[Lw': [R' D2 R, U]]",
    "UBR-UFL" : "[Lw D: [R' D' R, U]]",
    "UFL-BDL" : "[R' D2 R, U']",
    "UFL-BDR" : "[D': [R' D' R, U']]",
    "UFL-BUL" : "[U' R': [U', R' D' R]]",
    "UFL-BUR" : "[U' R: [R D R', U]]",
    "UFL-DBL" : "[R' D' R : [R U' R', D]]",
    "UFL-DBR" : "[R D' R': [R' D R, U']]",
    "UFL-DFL" : "[U' x': [R U R', D2]]",
    "UFL-DFR" : "[D R D' R': [R' D R, U']]",
    "UFL-FDL" : "[D: [R' D' R, U']]",
    "UFL-FDR" : "[D': [R' D R, U']]",
    "UFL-LDF" : "[R' D R, U']",
    "UFL-LFB" : "[U': [R D' R', U']]",
    "UFL-LUB" : "[U' R: [R D R', U2]]",
    "UFL-RDB" : "[U': [R D R', U']]",
    "UFL-RDF" : "[R' D' R, U']",
    "UFL-RUB" : "[U' R': [U2, R' D' R]]",
    "UFL-UBL" : "[R' D' U': [R' D R, U']]"
};

const oldEdgeComms = {
    "BD-BL" : "[U: [L, U M U']]",
    "BD-BR" : "Mirror BD-BL",
    "BD-DF" : "[D': [R F R', S']] ",
    "BD-DL" : "[U: [L2, U M U']]",
    "BD-DR" : "Mirror BD-DL",
    "BD-FL" : "[U: [L', U M U']]",
    "BD-FR" : "Mirror BD-FL",
    "BD-LB" : "[U' M: [R E' R', U]]",
    "BD-LD" : "[U x': [E, L' U' L]]",
    "BD-LF" : "[U' M : [R' E R, U]]",
    "BD-LU" : "[R' F R U': [M, U2]]",
    "BD-RB" : "Mirror BD-LB",
    "BD-RD" : "Mirror BD-LD",
    "BD-RF" : "Mirror BD-LF",
    "BD-RU" : "Mirror BD-LU",
    "BD-UB" : "[U' M' U : [M', U2]]",
    "BD-UL" : "[D: [L' E' L, U]]",
    "BD-UR" : "Mirror BD-UL",
    "BL-BR" : "[R U' R: [E', R2]]",
    "BL-DL" : "[D2 U' R: [E', R2]]",
    "BL-DR" : "[U' R: [E', R2]]",
    "BL-LD" : "[D: [M', U L U']]",
    "BL-LF" : "[L U L', E']",
    "BL-LU" : "[U' Lw U': [M', U2]]",
    "BL-RB" : "[L U L', E]",
    "BL-RD" : "[D': [M', U L U']]",
    "BL-RF" : "[L: [U, L E' L']]",
    "BL-RU" : "[M': [R E' R', U]]",
    "BR-DL" : "Mirror BL-DR",
    "BR-DR" : "Mirror BL-DL",
    "BR-LB" : "Mirror BL-RB",
    "BR-LD" : "Mirror BL-RD",
    "BR-LF" : "Mirror BL-RF",
    "BR-LU" : "Mirror BL-RU",
    "BR-RD" : "Mirror BL-LD",
    "BR-RF" : "Mirror BL-LF",
    "BR-RU" : "Mirror BL-LU",
    "BU-BD" : "[U' x': [R U R', E]]",
    "BU-BL" : "[U L U', M]",
    "BU-BR" : "Mirror BU-BL",
    "BU-DB" : "[U x': [E, R U R']]",
    "BU-DF" : "[U: [S, R' F' R]]",
    "BU-DL" : "[U L2 U', M]",
    "BU-DR" : "Mirror BU-DL",
    "BU-FD" : "[U': [R' F' R, S]]",
    "BU-FL" : "[U L' U', M]",
    "BU-FR" : "Mirror BU-FL",
    "BU-LB" : "[M', U' L U]",
    "BU-LD" : "[M', U' L2 U]",
    "BU-LF" : "[M', U' L' U]",
    "BU-LU" : "[L': [M', U' L U]]",
    "BU-RB" : "Mirror BU-LB",
    "BU-RD" : "Mirror BU-LD",
    "BU-RF" : "Mirror BU-LF",
    "BU-RU" : "Mirror BU-LU",
    "BU-UL" : "[L: [U L' U', M]]",
    "BU-UR" : "Mirror BU-UL",
    "DB-BL" : "[U' L U': [M, U2]]",
    "DB-BR" : "Mirror DB-BL",
    "DB-DL" : "[U' L2 U': [M, U2]]",
    "DB-DR" : "Mirror DB-DL",
    "DB-FL" : "[U' L' U': [M, U2]]",
    "DB-FR" : "Mirror DB-FL",
    "DB-LB" : "[M': [U' L U, M2]]",
    "DB-LD" : "[U : [L B' L', S']]",
    "DB-LF" : "[M': [U' L' U, M2]]",
    "DB-LU" : "[D: [S, L F' L']]",
    "DB-RB" : "Mirror DB-LB",
    "DB-RD" : "Mirror DB-LD",
    "DB-RF" : "Mirror DB-LF",
    "DB-RU" : "Mirror DB-LU",
    "DB-UL" : "[L' U' L U': [M, U2]]",
    "DB-UR" : "Mirror DB-UL",
    "DF-BL" : "[U' L U: [M', U2]]",
    "DF-BR" : "Mirror DF-BL",
    "DF-DB" : "[D2, M]",
    "DF-DL" : "[M' U2 M, D]",
    "DF-DR" : "Mirror DF-DL",
    "DF-FL" : "[U' L' U: [M', U2]]",
    "DF-FR" : "Mirror DF-FL",
    "DF-LB" : "[F: [L2, E']]",
    "DF-LD" : "[L F: [L2, E']]",
    "DF-LF" : "[L2 F: [L2, E']]",
    "DF-LU" : "[D': [S, L F' L']]",
    "DF-RB" : "Mirror DF-LB",
    "DF-RD" : "Mirror DF-LD",
    "DF-RF" : "Mirror DF-LF",
    "DF-RU" : "Mirror DF-LU",
    "DF-UL" : "[U', M U2 M]",
    "DF-UR" : "Mirror DF-UL",
    "DL-DR" : "[D': [M, D2]]",
    "DL-LB" : "[Uw L: [E, L2]]",
    "DL-LF" : "[U E L': [E', L2]]",
    "DL-LU" : "[S, L F' L']",
    "DL-RB" : "[Uw L': [E', L2]]",
    "DL-RD" : "[S', R F R']",
    "DL-RF" : "[U E L: [E, L2]]",
    "DL-RU" : "[Lw': [R' E R, U]]",
    "DL-UL" : "[L' U' L: [S', L2]]",
    "DR-LB" : "Mirror DL-RB",
    "DR-LD" : "Mirror DL-RD",
    "DR-LF" : "Mirror DL-RF",
    "DR-LU" : "Mirror DL-RU",
    "DR-RB" : "Mirror DL-LB",
    "DR-RF" : "Mirror DL-LF",
    "DR-RU" : "Mirror DL-LU",
    "DR-UR" : "Mirror DL-UL",
    "FD-BD" : "[U M': [U', M U2 M]]",
    "FD-BL" : "[U L U', M']",
    "FD-BR" : "Mirror FD-BL",
    "FD-DB" : "[D: [R F R', S']]",
    "FD-DL" : "[U L2 U', M']",
    "FD-DR" : "Mirror FD-DL",
    "FD-FL" : "[U L' U', M']",
    "FD-FR" : "Mirror FD-FL",
    "FD-LB" : "[M': [U' L U, M']]",
    "FD-LD" : "[U: [S, L F L']]",
    "FD-LF" : "[M': [U' L' U, M']]",
    "FD-LU" : "[Lw': [U' L U, M']]",
    "FD-RB" : "Mirror FD-LB",
    "FD-RD" : "Mirror FD-LD",
    "FD-RF" : "Mirror FD-LF",
    "FD-RU" : "Mirror FD-LU",
    "FD-UB" : "[R' F': [E, R U R']]",
    "FD-UL" : "[Lw': [M, U L U']]",
    "FD-UR" : "Mirror FD-UL",
    "FL-BL" : "[U' L: [S', L2]]",
    "FL-BR" : "[R U' R': [E, R2]]",
    "FL-DL" : "[D2 U' R': [E, R2]]",
    "FL-DR" : "[U' R': [E, R2]]",
    "FL-FR" : "[R' U' R': [E, R2]]",
    "FL-LB" : "[L' U L, E']",
    "FL-LD" : "[D: [M', U L' U']]",
    "FL-LU" : "[M' U: [U, R' E R]]",
    "FL-RB" : "[L': [U, L' E L]] ",
    "FL-RD" : "[D': [M', U L' U']]",
    "FL-RF" : "[L' U L, E]",
    "FL-RU" : "[S U' R': [E, R2]]",
    "FR-BL" : "Mirror FL-BR",
    "FR-BR" : "Mirror FL-BL",
    "FR-DL" : "Mirror FL-DR",
    "FR-DR" : "Mirror FL-DL",
    "FR-LB" : "Mirror FL-RB",
    "FR-LD" : "Mirror FL-RD",
    "FR-LF" : "Mirror FL-RF",
    "FR-LU" : "Mirror FL-RU",
    "FR-RB" : "Mirror FL-LB",
    "FR-RD" : "Mirror FL-LD",
    "FR-RU" : "Mirror FL-LU",
    "LB-RB" : "[Uw R: [S, R2]]",
    "LD-LB" : "[U S' U', L']",
    "LD-RB" : "[M' U' L: [E, L2]]",
    "LD-RD" : "[R' F R': [S', R2]]",
    "LF-LB" : "[E' R U' R: [E', R2]]",
    "LF-LD" : "[L, U S' U']",
    "LF-RB" : "[Rw U R': [E, R2]]",
    "LF-RD" : "[M' U R': [E, R2]]",
    "LF-RF" : "[U E R': [S, R2]]",
    "LU-LB" : "[S: [U', R E' R']]",
    "LU-LD" : "[S' D': [M, D2]]",
    "LU-LF" : "[S: [U', R' E R]]",
    "LU-RB" : "[Rw' U: [M', U2]]",
    "LU-RD" : "[R' F R: [S, R2]]",
    "LU-RF" : "[R M U: [M', U2]]",
    "LU-RU" : "[M U: [M', U2]]",
    "RD-LB" : "Mirror LD-RB",
    "RD-LD" : "Mirror LD-RD",
    "RD-RB" : "Mirror LD-LB",
    "RF-LB" : "Mirror LF-RB",
    "RF-LD" : "Mirror LF-RD",
    "RF-LF" : "Mirror LF-RF",
    "RF-RB" : "Mirror LF-LB",
    "RF-RD" : "Mirror LF-LD",
    "RU-LB" : "Mirror LU-RB",
    "RU-LD" : "Mirror LU-RD",
    "RU-LF" : "Mirror LU-RF",
    "RU-RB" : "Mirror LU-LB",
    "RU-RD" : "Mirror LU-LD",
    "RU-RF" : "Mirror LU-LF",
    "UB-BL" : "[L' U: [S', L2]]",
    "UB-BR" : "Mirror UB-BL",
    "UB-DB" : "[M, U2]",
    "UB-DF" : "[U2, M']",
    "UB-DL" : "[U: [S', L2]]",
    "UB-DR" : "Mirror UB-DL",
    "UB-FL" : "[L U: [S', L2]]",
    "UB-FR" : "Mirror UB-FL",
    "UB-LB" : "[U': [R E' R', U2]]",
    "UB-LD" : "[U: [L' E' L, U2]]",
    "UB-LF" : "[U': [R' E R , U2]]",
    "UB-LU" : "[U' M U': [M', U2]]",
    "UB-RB" : "Mirror UB-LB",//???
    "UB-RD" : "Mirror UB-LD",
    "UB-RF" : "Mirror UB-LF",
    "UB-RU" : "Mirror UB-LU",
    "UB-UL" : "[U' M2 U: [M, U2]]",
    "UB-UR" : "Mirror UB-UL",
    "UL-BL" : "[U': [R' E2 R, U']]",
    "UL-BR" : "[U, L E2 L']",
    "UL-DL" : "[L U' L: [S', L2]]",
    "UL-DR" : "[Rw2 U': [M, U2]]",
    "UL-FL" : "[U': [R E2 R', U']]",
    "UL-FR" : "[U, L' E2 L]",
    "UL-LB" : "[U': [R E' R', U']]",
    "UL-LD" : "[U, L' E' L]",
    "UL-LF" : "[U': [R' E R, U']]",
    "UL-RB" : "[U, L' E L]",
    "UL-RD" : "[U': [R E R', U']]",
    "UL-RF" : "[U, L E' L']",
    "UL-RU" : "[S, R' F R]",
    "UL-UR" : "[M2 U': [M, U2]]",
    "UR-BL" : "Mirror UL-BR",
    "UR-BR" : "Mirror UL-BL",
    "UR-DL" : "Mirror UL-DR",
    "UR-DR" : "Mirror UL-DL",
    "UR-FL" : "Mirror UL-FR",
    "UR-FR" : "Mirror UL-FL",
    "UR-LB" : "Mirror UL-RB",
    "UR-LD" : "Mirror UL-RD",
    "UR-LF" : "Mirror UL-RF",
    "UR-LU" : "Mirror UL-RU",
    "UR-RB" : "Mirror UL-LB",
    "UR-RD" : "Mirror UL-LD",
    "UR-RF" : "Mirror UL-LF"
};

const cornerComms = {
    "UBL-UBL" : "",
    "UBL-UBR" : "[R D R' U' : [R D' R' , U2]]",
    "UBL-UFL" : "[R' D' U : [U , R' D R]]",
    "UBL-LUB" : "",
    "UBL-LUF" : "[F : [U2 , F' R F R']]",
    "UBL-LDF" : "[R' D R , U2]",
    "UBL-LDB" : "[U' : [R D' R' , U2]]",
    "UBL-FUL" : "[l' D' U : [R D R' , U2]]",
    "UBL-FDR" : "[D U' : [R D R' , U2]]",
    "UBL-FDL" : "[D' U' : [R D' R' , U2]]",
    "UBL-RUB" : "[R' U D R2 : [U' , R' D' R]]",
    "UBL-RDB" : "[U' : [R D R' , U2]]",
    "UBL-RDF" : "[R' D' R , U2]",
    "UBL-BUR" : "[R' U D : [R D R' , U2]]",
    "UBL-BUL" : "",
    "UBL-BDL" : "[D' U' : [R D R' , U2]]",
    "UBL-BDR" : "[D U' : [R D' R' , U2]]",
    "UBL-DFL" : "[D R2' : [U , R2 D R2' D' R2]]",
    "UBL-DFR" : "[R2 : [U , R2' D R2 D' R2']]",
    "UBL-DBR" : "[D' R2' : [U , R2 D R2' D' R2]]",
    "UBL-DBL" : "[R' D' U' R2 : [U' , R' D R]]",
    "UBR-UBL" : "[R D R' U : [R D' R' , U2]]",
    "UBR-UBR" : "",
    "UBR-UFL" : "[R F' R2' : [D , R U R']]",
    "UBR-LUB" : "[R : [U , R D R']]",
    "UBR-LUF" : "[R2 : [D' , R U' R']]",
    "UBR-LDF" : "[R' D R , U]",
    "UBR-LDB" : "[U' , R D' R']",
    "UBR-FUL" : "[R2 U' : [D' , R U R']]",
    "UBR-FDR" : "[D' : [R' D R , U]]",
    "UBR-FDL" : "[D : [R' D' R , U]]",
    "UBR-RUB" : "",
    "UBR-RDB" : "[U' , R D R']",
    "UBR-RDF" : "[R' D' R , U]",
    "UBR-BUR" : "",
    "UBR-BUL" : "[R2 U : [R' U' R , D]]",
    "UBR-BDL" : "[D' : [U' , R D R']]",
    "UBR-BDR" : "[D : [U' , R D' R']]",
    "UBR-DFL" : "[R F' : [R' U' R , D]]",
    "UBR-DFR" : "[R' D R U' R D' R' , U]",
    "UBR-DBR" : "[U' , R D' R' U R' D R]",
    "UBR-DBL" : "[R' B : [D' , R U R']]",
    "UFL-UBL" : "[R' U' D' : [R' D R , U']]",
    "UFL-UBR" : "[R F' R' : [U , R' D R]]",
    "UFL-UFL" : "",
    "UFL-LUB" : "[U' R2 : [D , R' U2 R]]",
    "UFL-LUF" : "",
    "UFL-LDF" : "[R' D R , U']",
    "UFL-LDB" : "[U' : [R D' R' , U']]",
    "UFL-FUL" : "",
    "UFL-FDR" : "[D' : [R' D R , U']]",
    "UFL-FDL" : "[D : [R' D' R , U']]",
    "UFL-RUB" : "[U' R' : [U2 , R' D' R]]",
    "UFL-RDB" : "[U' : [R D R' , U']]",
    "UFL-RDF" : "[R' D' R , U']",
    "UFL-BUR" : "[R' D' : [U' , R' D R]]",
    "UFL-BUL" : "[U' R' : [U' , R' D' R]]",
    "UFL-BDL" : "[D : [R' D R , U']]",
    "UFL-BDR" : "[D' : [R' D' R , U']]",
    "UFL-DFL" : "[R' U' R : [F2 , R' U R U']]",
    "UFL-DFR" : "[R' D R U' R D' R' , U']",
    "UFL-DBR" : "[R D' R2' : [D , R U' R']]",
    "UFL-DBL" : "[R' D' R2 : [U' , R' D R]]",
    "LUB-UBL" : "",
    "LUB-UBR" : "[R2 : [D , R' U R]]",
    "LUB-UFL" : "[U' R : [U2 , R D R']]",
    "LUB-LUB" : "",
    "LUB-LUF" : "[L , U' R' U]",
    "LUB-LDF" : "[U R' : [U' , R' D R]]",
    "LUB-LDB" : "[R D' : [R D R' , U]]",
    "LUB-FUL" : "[l' U : [R D' R' , U2]]",
    "LUB-FDR" : "[U D' R' : [U' , R' D R]]",
    "LUB-FDL" : "[R U : [R' D R , U]]",
    "LUB-RUB" : "[R' D R2 D' R2' : [U , R2 D R2' D' R2]]",
    "LUB-RDB" : "[U' R2 : [U' , R' D' R]]",
    "LUB-RDF" : "[U R' U2 : [R D R' , U]]",
    "LUB-BUR" : "[R' , F' L F]]",
    "LUB-BUL" : "",
    "LUB-BDL" : "[U D R' : [U' , R' D R]]",
    "LUB-BDR" : "[R U : [R' D' R , U]]",
    "LUB-DFL" : "[D' R2 : [D' , R' U R]]",
    "LUB-DFR" : "[U R' D' : [U' , R' D' R]]",
    "LUB-DBR" : "[D R2 : [D' , R' U R]]",
    "LUB-DBL" : "[R2 : [D' , R' U R]]",
    "LUF-UBL" : "[R F R' : [U2 , R F' R' F]]",
    "LUF-UBR" : "[R' : [U' , R' D' R]]",
    "LUF-UFL" : "",
    "LUF-LUB" : "[U' R' U , L]",
    "LUF-LUF" : "",
    "LUF-LDF" : "[R' U' : [D , R U R']]",
    "LUF-LDB" : "[U' R U' : [D' , R' U R]]",
    "LUF-FUL" : "",
    "LUF-FDR" : "[R : [F , R' U R U']]",
    "LUF-FDL" : "[D R' U' : [D' , R U R']]",
    "LUF-RUB" : "[R U' D' R' : [D , R' U R]]",
    "LUF-RDB" : "[D' R : [F , R' U R U']]",
    "LUF-RDF" : "[R' U' : [D' , R U R']]",
    "LUF-BUR" : "[R' F : [R U R' , D]]",
    "LUF-BUL" : "[l U' l' , F]",
    "LUF-BDL" : "[l U2 l', F]",
    "LUF-BDR" : "[D' R' U' : [D' , R U R']]",
    "LUF-DFL" : "[U' R' U : [R U' R' , D]]",
    "LUF-DFR" : "[U' D' R' U : [R U' R' , D]]",
    "LUF-DBR" : "[R U' R' : [D , R' U R]]",
    "LUF-DBL" : "[U' D R' U : [R U' R' , D]]",
    "LDF-UBL" : "[U2 , R' D R]",
    "LDF-UBR" : "[U , R' D R]",
    "LDF-UFL" : "[U' , R' D R]",
    "LDF-LUB" : "[U R2' : [D , R U' R']]",
    "LDF-LUF" : "[R' U' : [R U R' , D]]",
    "LDF-LDF" : "",
    "LDF-LDB" : "[D R' : [F' , R D' R']]",
    "LDF-FUL" : "[D R' : [F2 , R D' R' D]]",
    "LDF-FDR" : "[U : [D , R U' R']]",
    "LDF-FDL" : "",
    "LDF-RUB" : "[U R U : [R' D R , U2]]",
    "LDF-RDB" : "[U D : [R U' R' , D2]]",
    "LDF-RDF" : "[U R' D : [R U' R' , D2]]",
    "LDF-BUR" : "[R' U : [R U' R' , D]]",
    "LDF-BUL" : "[U' R' D : [U' , R' D' R]]",
    "LDF-BDL" : "[U D : [R U' R' , D]]",
    "LDF-BDR" : "[R' D R : [D' , R U R']]",
    "LDF-DFL" : "",
    "LDF-DFR" : "[U D R D' : [U' , R' D R]]",
    "LDF-DBR" : "[U R : [D , R U' R']]",
    "LDF-DBL" : "[D U R U' : [F2 , U R' U' R]]",
    "LDB-UBL" : "[U : [R D' R' , U2]]",
    "LDB-UBR" : "[R D' R' , U']",
    "LDB-UFL" : "[U2 : [R D' R' , U]]",
    "LDB-LUB" : "[R D' : [U , R D R']]",
    "LDB-LUF" : "[U' R U' : [R' U R , D']]",
    "LDB-LDF" : "[R' D : [F' , D' R D R']]",
    "LDB-LDB" : "",
    "LDB-FUL" : "[R U' D : [R' D R , U2]]",
    "LDB-FDR" : "[U R U' : [R D' R' , U']]",
    "LDB-FDL" : "[D2 : [R U R' , D']]",
    "LDB-RUB" : "[U R2 : [D' , R' U2 R]]",
    "LDB-RDB" : "[R D' : [R' U' R , D2]]",
    "LDB-RDF" : "[D2' , R U R']",
    "LDB-BUR" : "[U' L U , R]",
    "LDB-BUL" : "[U2 R2 : [D' , R' U R]]",
    "LDB-BDL" : "",
    "LDB-BDR" : "[D2 : [R U R' , D]]",
    "LDB-DFL" : "[D' R D U' : [R' U R , D2]]",
    "LDB-DFR" : "[D2 R2 : [D' , R' U' R]]",
    "LDB-DBR" : "[R D' R2' : [D , R U' R']]",
    "LDB-DBL" : "",
    "FUL-UBL" : "[l' U' D' : [R D R' , U2]]",
    "FUL-UBR" : "[R2 U' : [R U R' , D']]",
    "FUL-UFL" : "",
    "FUL-LUB" : "[l' U' : [R D' R' , U2]]",
    "FUL-LUF" : "",
    "FUL-LDF" : "[R' D : [F2 , D' R D R']]",
    "FUL-LDB" : "[R U D : [R' D R , U2]]",
    "FUL-FUL" : "",
    "FUL-FDR" : "[D' R' D : [F2 , D' R D R']]",
    "FUL-FDL" : "[R U : [R' D R , U2]]",
    "FUL-RUB" : "[R' : [U' , R2 D' R2 D R2]]",
    "FUL-RDB" : "[R U D' : [R' D R , U2]]",
    "FUL-RDF" : "[D R U : [R' D' R , U2]]",
    "FUL-BUR" : "[R U D' : [R' D' R , U2]]",
    "FUL-BUL" : "[R2 U' R U : [R' D' R , U2]]",
    "FUL-BDL" : "[D R' D : [F2 , D' R D R']]",
    "FUL-BDR" : "[R U : [R' D' R , U2]]",
    "FUL-DFL" : "[R U D : [R' D' R , U2]]",
    "FUL-DFR" : "[D' L : [F2 , L' D L D']]",
    "FUL-DBR" : "[D R2 : [D' , R' U2 R]]",
    "FUL-DBL" : "[R2 U : [D' , R' U R]]",
    "FDR-UBL" : "[U D : [R D R' , U2]]",
    "FDR-UBR" : "[D' : [U , R' D R]]",
    "FDR-UFL" : "[D' : [U' , R' D R]]",
    "FDR-LUB" : "[U D' R2' : [D , R U' R']]",
    "FDR-LUF" : "[U R U' : [F , U R' U' R]]",
    "FDR-LDF" : "[U : [R U' R' , D]]",
    "FDR-LDB" : "[l' U : [R U' R' , D]]",
    "FDR-FUL" : "[R' : [F2 , R D' R' D]]",
    "FDR-FDR" : "",
    "FDR-FDL" : "[R' : [F' , R D' R' D]]",
    "FDR-RUB" : "[U' R' U : [R D R' , U2]]",
    "FDR-RDB" : "[U : [R U' R' , D']]",
    "FDR-RDF" : "",
    "FDR-BUR" : "[D' R' U : [R U' R' , D]]",
    "FDR-BUL" : "[U' R' U2 : [R D R' , U]]",
    "FDR-BDL" : "[U : [R U' R' , D2']]",
    "FDR-BDR" : "[R U R' U' : [D' , R U R']]",
    "FDR-DFL" : "[U R U' : [F2 , U R' U' R]]",
    "FDR-DFR" : "",
    "FDR-DBR" : "[U R' D' : [U' , R' D R]]",
    "FDR-DBL" : "[D U' R2' : [D , R U R']]",
    "FDL-UBL" : "[D' U : [R D' R' , U2]]",
    "FDL-UBR" : "[D : [U , R' D' R]]",
    "FDL-UFL" : "[D : [U' , R' D' R]]",
    "FDL-LUB" : "[R U2 : [R' D R , U']]",
    "FDL-LUF" : "[D R' U' : [R U R' , D']]",
    "FDL-LDF" : "",
    "FDL-LDB" : "[D : [R U R' , D]]",
    "FDL-FUL" : "[R U' : [R' D R , U2]]",
    "FDL-FDR" : "[D' R' D : [F' , D' R D R']]",
    "FDL-FDL" : "",
    "FDL-RUB" : "[U R U D : [R' D' R , U2]]",
    "FDL-RDB" : "[R D2 : [R' U' R , D']]",
    "FDL-RDF" : "[D , R U R']",
    "FDL-BUR" : "[R' F : [R U' R' , D]]",
    "FDL-BUL" : "[D R' : [D , R' U R]]",
    "FDL-BDL" : "[D' R D' : [R' U' R , D2]]",
    "FDL-BDR" : "[D : [R U R' , D2]]",
    "FDL-DFL" : "",
    "FDL-DFR" : "[L' U : [F2 , U' L U L']]",
    "FDL-DBR" : "[D R : [R D' R' , U']]",
    "FDL-DBL" : "[D R D : [U , R' D' R]]",
    "RUB-UBL" : "[R' U D R : [D' , R U' R']]",
    "RUB-UBR" : "",
    "RUB-UFL" : "[U' R2 U : [R' U' R , D]]",
    "RUB-LUB" : "[R : [U , R2 D R2 D' R2]]",
    "RUB-LUF" : "[R U' D' R2' : [U , R D R']]",
    "RUB-LDF" : "[U R U' : [R' D R , U2]]",
    "RUB-LDB" : "[U R : [U2 , R D' R']]",
    "RUB-FUL" : "[R D' R2' D R2 : [U' , R2' D' R2 D R2']]",
    "RUB-FDR" : "[U' R' U' : [R D R' , U2]]",
    "RUB-FDL" : "[U R U' D : [R' D' R , U2]]",
    "RUB-RUB" : "",
    "RUB-RDB" : "[U R U' : [R' D' R , U2]]",
    "RUB-RDF" : "[U' R' D U' : [R D' R' , U2]]",
    "RUB-BUR" : "",
    "RUB-BUL" : "[U R2 U' : [D' , R U R']]",
    "RUB-BDL" : "[U' R' U' : [R D' R' , U2]]",
    "RUB-BDR" : "[D' U' R' U' D : [R D' R' , U2]]",
    "RUB-DFL" : "[U' R2' : [D , R U2 R']]",
    "RUB-DFR" : "[U' D' R2' : [D , R U2 R']]",
    "RUB-DBR" : "[U R U' D' : [R' D R , U2]]",
    "RUB-DBL" : "[D U' R2' : [D , R U2 R']]",
    "RDB-UBL" : "[U : [R D R' , U2]]",
    "RDB-UBR" : "[R D R' , U']",
    "RDB-UFL" : "[U2 : [R D R' , U]]",
    "RDB-LUB" : "[U' R : [D' , R U' R']]",
    "RDB-LUF" : "[D' U R U' : [F , U R' U' R]]",
    "RDB-LDF" : "[U D' : [R U' R' , D2]]",
    "RDB-LDB" : "[R D : [R' U R , D2]]",
    "RDB-FUL" : "[R D' U' : [R' D R , U2]]",
    "RDB-FDR" : "[U : [D' , R U' R']]",
    "RDB-FDL" : "[R D : [R' U' R , D]]",
    "RDB-RUB" : "[U R U : [R' D' R , U2]]",
    "RDB-RDB" : "",
    "RDB-RDF" : "[R' U : [D' , R U R']]",
    "RDB-BUR" : "[U' R U : [R' U' R , D]]",
    "RDB-BUL" : "[R' U : [R' D' R , U]]",
    "RDB-BDL" : "[U' : [R' U' R , D']]",
    "RDB-BDR" : "",
    "RDB-DFL" : "[U' R2' : [D , R U R']]",
    "RDB-DFR" : "[D' U R U' : [F2 , U R' U' R]]",
    "RDB-DBR" : "",
    "RDB-DBL" : "[U : [D' R' D , L2]]",
    "RDF-UBL" : "[U2 , R' D' R]",
    "RDF-UBR" : "[U , R' D' R]",
    "RDF-UFL" : "[U' , R' D' R]",
    "RDF-LUB" : "[U R' U' : [R D R' , U']]",
    "RDF-LUF" : "[R' U' : [R U R' , D']]",
    "RDF-LDF" : "[U R' D' : [R U' R' , D2]]",
    "RDF-LDB" : "[R U R' , D2]",
    "RDF-FUL" : "[D R U' : [R' D' R , U2]]",
    "RDF-FDR" : "",
    "RDF-FDL" : "[R U R' , D]",
    "RDF-RUB" : "[U' R' D U : [R D' R' , U2]]",
    "RDF-RDB" : "[R' U : [R U R' , D']]",
    "RDF-RDF" : "",
    "RDF-BUR" : "[R' U : [R U' R' , D']]",
    "RDF-BUL" : "[R' : [D , R' U R]]",
    "RDF-BDL" : "[U R' D' : [R U' R' , D']]",
    "RDF-BDR" : "[R U R' , D']",
    "RDF-DFL" : "[R D : [U , R' D' R]]",
    "RDF-DFR" : "",
    "RDF-DBR" : "[R : [U , R' D R U' R D' R']]",
    "RDF-DBL" : "[R2 : [D' , R' U' R]]",
    "BUR-UBL" : "[R' U' D : [R D R' , U2]]",
    "BUR-UBR" : "",
    "BUR-UFL" : "[R' D' : [R' D R , U']]",
    "BUR-LUB" : "[F' L F , R']",
    "BUR-LUF" : "[R' F : [D , R U R']]",
    "BUR-LDF" : "[R' U : [D , R U' R']]",
    "BUR-LDB" : "[R , U' L U]",
    "BUR-FUL" : "[R D' U' : [R' D' R , U2]]",
    "BUR-FDR" : "[D' R' U : [D , R U' R']]",
    "BUR-FDL" : "[R' F : [D , R U' R']]",
    "BUR-RUB" : "",
    "BUR-RDB" : "[U' R U : [D , R' U' R]]",
    "BUR-RDF" : "[R' U : [D' , R U' R']]",
    "BUR-BUR" : "",
    "BUR-BUL" : "[R , U' L' U]",
    "BUR-BDL" : "[D R' U : [D , R U' R']]",
    "BUR-BDR" : "[R U' : [R' U R , D]]",
    "BUR-DFL" : "[D' R U' : [R' U R , D']]",
    "BUR-DFR" : "[U R' U' : [R U R' , D']]",
    "BUR-DBR" : "[D R U' : [R' U R , D']]",
    "BUR-DBL" : "[R U' : [R' U R , D']]",
    "BUL-UBL" : "",
    "BUL-UBR" : "[R2 U : [D , R' U' R]]",
    "BUL-UFL" : "[U' R2' : [D' , R U' R']]",
    "BUL-LUB" : "",
    "BUL-LUF" : "[F , l U' l']",
    "BUL-LDF" : "[U' R' D : [R' D' R , U']]",
    "BUL-LDB" : "[U2 R : [U , R D' R']]",
    "BUL-FUL" : "[R2 U' R U' : [R' D' R , U2]]",
    "BUL-FDR" : "[D R' U2 : [R' D' R , U']]",
    "BUL-FDL" : "[D R2' : [U , R D R']]",
    "BUL-RUB" : "[U R2 U' : [R U R' , D']]",
    "BUL-RDB" : "[R' U2 : [R' D' R , U']]",
    "BUL-RDF" : "[R2' : [U , R D R']]",
    "BUL-BUR" : "[U' L' U , R]",
    "BUL-BUL" : "",
    "BUL-BDL" : "[U' R' U' : [R D' R' , U']]",
    "BUL-BDR" : "[D' R2' : [U , R D R']]",
    "BUL-DFL" : "[U' R2' : [D , R U' R']]",
    "BUL-DFR" : "[U' D' R2' : [D , R U' R']]",
    "BUL-DBR" : "[U R : [D' , R U' R']]",
    "BUL-DBL" : "[R2 U : [D' , R' U' R]]",
    "BDL-UBL" : "[U D' : [R D R' , U2]]",
    "BDL-UBR" : "[D' : [R D R' , U']]",
    "BDL-UFL" : "[D : [U' , R' D R]]",
    "BDL-LUB" : "[U D R2' : [D , R U' R']]",
    "BDL-LUF" : "[F , l U2 l']",
    "BDL-LDF" : "[U D2 : [R U' R' , D']]",
    "BDL-LDB" : "",
    "BDL-FUL" : "[D' R D' U' : [R' D R , U2]]",
    "BDL-FDR" : "[U : [D2 , R U' R']]",
    "BDL-FDL" : "[D' R D : [R' U' R , D2]]",
    "BDL-RUB" : "[U' R' U : [R D' R' , U2]]",
    "BDL-RDB" : "[U' : [D' , R' U' R]]",
    "BDL-RDF" : "[U R' D2 : [R U' R' , D]]",
    "BDL-BUR" : "[D R' U : [R U' R' , D]]",
    "BDL-BUL" : "[U' R' U2 : [R D' R' , U]]",
    "BDL-BDL" : "",
    "BDL-BDR" : "[U' : [R' , U' L U]]",
    "BDL-DFL" : "[U' D' R' D' : [U' , R D R']]",
    "BDL-DFR" : "[U' D' R2' : [D , R U R']]",
    "BDL-DBR" : "[U R : [D2 , R U' R']]",
    "BDL-DBL" : "",
    "BDR-UBL" : "[U D : [R D' R' , U2]]",
    "BDR-UBR" : "[D : [R D' R' , U']]",
    "BDR-UFL" : "[D' : [U' , R' D' R]]",
    "BDR-LUB" : "[R U2 : [R' D' R , U']]",
    "BDR-LUF" : "[D' R' U' : [R U R' , D']]",
    "BDR-LDF" : "[R' D R2 : [U , R' D' R]]",
    "BDR-LDB" : "[D' : [R U R' , D']]",
    "BDR-FUL" : "[R U' : [R' D' R , U2]]",
    "BDR-FDR" : "[R U R' U' : [R U R' , D']]",
    "BDR-FDL" : "[D' : [R U R' , D2]]",
    "BDR-RUB" : "[U D R2 : [D' , R' U2 R]]",
    "BDR-RDB" : "",
    "BDR-RDF" : "[D' , R U R']",
    "BDR-BUR" : "[R U' : [D , R' U R]]",
    "BDR-BUL" : "[D' R' : [D , R' U R]]",
    "BDR-BDL" : "[U2 : [L , U R' U']]",
    "BDR-BDR" : "",
    "BDR-DFL" : "[D' R2 : [D' , R' U' R]]",
    "BDR-DFR" : "[D' R D : [U , R' D' R]]",
    "BDR-DBR" : "",
    "BDR-DBL" : "[R U' D : [R' U R , D2]]",
    "DFL-UBL" : "[D2 R2' D' R2 : [U , R2' D R2 D' R2']]",
    "DFL-UBR" : "[R F' : [D , R' U' R]]",
    "DFL-UFL" : "[U' : [F2 , U R' U' R]]",
    "DFL-LUB" : "[D' R : [U , R D' R']]",
    "DFL-LUF" : "[U' R' U : [D , R U' R']]",
    "DFL-LDF" : "",
    "DFL-LDB" : "[D' R D' U' : [R' U R , D2]]",
    "DFL-FUL" : "[R D U' : [R' D' R , U2]]",
    "DFL-FDR" : "[R : [F2 , R' U R U']]",
    "DFL-FDL" : "",
    "DFL-RUB" : "[U' R' : [U2 , R' D R]]",
    "DFL-RDB" : "[U' R' : [U , R' D R]]",
    "DFL-RDF" : "[R D : [R' D' R , U]]",
    "DFL-BUR" : "[D' R U' : [D' , R' U R]]",
    "DFL-BUL" : "[U' R' : [U' , R' D R]]",
    "DFL-BDL" : "[D' U' R' D' : [R D R' , U']]",
    "DFL-BDR" : "[D' R : [U' , R D' R']]",
    "DFL-DFL" : "",
    "DFL-DFR" : "[D , R2' U R2 U' R2']]",
    "DFL-DBR" : "[R2' U' R2 : [D , R2' U R2 U' R2']]",
    "DFL-DBL" : "[R U' D2 : [R' U R , D]]",
    "DFR-UBL" : "[D R2' D' R2 : [U , R2' D R2 D' R2]]",
    "DFR-UBR" : "[U , R' D R U' R D' R']",
    "DFR-UFL" : "[U' , R' D U' R D' R']",
    "DFR-LUB" : "[U R' D' : [R' D' R , U']]",
    "DFR-LUF" : "[U' D' R' U : [D , R U' R']]",
    "DFR-LDF" : "[U D R D' : [R' D R , U']]",
    "DFR-LDB" : "[D2 R : [U' , R D' R']]",
    "DFR-FUL" : "[L D' : [F2 , D L' D' L]]",
    "DFR-FDR" : "",
    "DFR-FDL" : "[U L' : [F2 , L U' L' U]]",
    "DFR-RUB" : "[U' D' R' : [U2 , R' D R]]",
    "DFR-RDB" : "[D' R : [F2 , R' U R U']]",
    "DFR-RDF" : "",
    "DFR-BUR" : "[U R' U' : [D' , R U R']]",
    "DFR-BUL" : "[U' D' R' : [U' , R' D R]]",
    "DFR-BDL" : "[U' D' R' : [U , R' D R]]",
    "DFR-BDR" : "[D' R D : [R' D' R , U]]",
    "DFR-DFL" : "[R2' U R2 U' R2' , D]",
    "DFR-DFR" : "",
    "DFR-DBR" : "[R2' U R2 U' R2' , D']]",
    "DFR-DBL" : "[R2' : [D' , R2 U' R2' U R2]]",
    "DBR-UBL" : "[R2' D' R2 : [U , R2' D R2 D' R2']]",
    "DBR-UBR" : "[R D' R' U R' D R , U']",
    "DBR-UFL" : "[R D' R' : [U' , R' D R]]",
    "DBR-LUB" : "[D R : [U , R D' R']]",
    "DBR-LUF" : "[R U' R2' : [U , R D R']]",
    "DBR-LDF" : "[U R2 : [U' , R' D R]]",
    "DBR-LDB" : "[R D' R' : [U , R' D R]]",
    "DBR-FUL" : "[D R : [U2 , R D' R']]",
    "DBR-FDR" : "[U R D' : [R' D R , U']]",
    "DBR-FDL" : "[D R : [U' , R D' R']]",
    "DBR-RUB" : "[U R U D' : [R' D R , U2]]",
    "DBR-RDB" : "",
    "DBR-RDF" : "[R : [R' D R U' R D' R' , U]]",
    "DBR-BUR" : "[D R U' : [D' , R' U R]]",
    "DBR-BUL" : "[U R2 : [U' , R' D' R]]",
    "DBR-BDL" : "[U R2 : [U' , R' D2 R]]",
    "DBR-BDR" : "",
    "DBR-DFL" : "[U' R2' : [D , R2 U R2' U' R2]]",
    "DBR-DFR" : "[D' , R2' U R2 U' R2']]",
    "DBR-DBR" : "",
    "DBR-DBL" : "[R U' R2' : [U , R D' R']]",
    "DBL-UBL" : "[R' U' D' R : [D , R U' R']]",
    "DBL-UBR" : "[R' B : [R U R' , D']]",
    "DBL-UFL" : "[R' D' R : [D , R U' R']]",
    "DBL-LUB" : "[R : [U , R D' R']]",
    "DBL-LUF" : "[U' D R' U : [D , R U' R']]",
    "DBL-LDF" : "[D R : [F2 , R' U R U']]",
    "DBL-LDB" : "",
    "DBL-FUL" : "[R2 U : [R' U R , D']]",
    "DBL-FDR" : "[D U' R' : [U , R' D R]]",
    "DBL-FDL" : "[D R D : [R' D' R , U]]",
    "DBL-RUB" : "[D U' R' : [U2 , R' D R]]",
    "DBL-RDB" : "[U' R' D' : [R D R' , U']]",
    "DBL-RDF" : "[R : [U' , R D' R']]",
    "DBL-BUR" : "[R U' : [D' , R' U R]]",
    "DBL-BUL" : "[R2 U : [R' U' R , D']]",
    "DBL-BDL" : "",
    "DBL-BDR" : "[R U' D' : [R' U R , D2]]",
    "DBL-DFL" : "[R U' D' : [R' U R , D']]",
    "DBL-DFR" : "[U' R2' U R2 : [D' , R2' U' R2 U R2']]",
    "DBL-DBR" : "[R U' R' : [D' , R' U R]]",
    "DBL-DBL" : ""
}
const edgeComms = {
    "UB-UB" : "",
    "UB-UR" : "[R2 U' : [S , R2']]",
    "UB-UL" : "[L2' U : [S' , L2]]",
    "UB-LU" : "[U' M U' : [M' , U2]]",
    "UB-LF" : "[U' : [R' E R , U2]]",
    "UB-LD" : "[U : [L' E' L , U2']]",
    "UB-LB" : "[U' : [R E' R' , U2]]",
    "UB-FR" : "[R' U' : [S , R2']]",
    "UB-FD" : "[R' F' : [R U R' , E]]",
    "UB-FL" : "[L U : [S' , L2']]",
    "UB-RU" : "[U M U : [M' , U2']]",
    "UB-RB" : "[U : [L' E L , U2']]",
    "UB-RD" : "[U' : [R E R' , U2]]",
    "UB-RF" : "[U : [L E' L' , U2']]",
    "UB-BU" : "",
    "UB-BL" : "[L' U' : [L2 , S']]",
    "UB-BD" : "[U' R' B R : [S , R2']]",
    "UB-BR" : "[R U' : [S , R2']]",
    "UB-DF" : "[U2 , M']",
    "UB-DR" : "[U' : [S , R2']]",
    "UB-DB" : "[M , U2]",
    "UB-DL" : "[U : [S' , L2']]",
    "UR-UB" : "[R2 U' : [R2' , S]]",
    "UR-UR" : "",
    "UR-UL" : "[M2 U : [M , U2']]",
    "UR-LU" : "[S' , L F' L']",
    "UR-LF" : "[U' , R' E R]",
    "UR-LD" : "[U : [L' E' L , U]]",
    "UR-LB" : "[U' , R E' R']",
    "UR-FR" : "[E' : [U' , R' E R]]",
    "UR-FD" : "[r : [U' R' U , M]]",
    "UR-FL" : "[U' , R E2 R']",
    "UR-RU" : "",
    "UR-RB" : "[U : [L' E L , U]",
    "UR-RD" : "[U' , R E R']",
    "UR-RF" : "[U : [L E' L' , U]",
    "UR-BU" : "[R : [M , U' R' U]]",
    "UR-BL" : "[U' , R' E2 R]",
    "UR-BD" : "(U M U M') * 2",
    "UR-BR" : "[u' : [R E' R' , U]]",
    "UR-DF" : "[L F : [L' S' L , F2']]",
    "UR-DR" : "[R' U R' : [S , R2]]",
    "UR-DB" : "[r M' : [U' R' U , M2]]",
    "UR-DL" : "[R U L' : [E , L2]]",
    "UL-UB" : "[L2' U : [L2 , S']]",
    "UL-UR" : "[M2 U' : [M , U2]]",
    "UL-UL" : "",
    "UL-LU" : "",
    "UL-LF" : "[U' : [R' E R , U']]",
    "UL-LD" : "[U , L' E' L]",
    "UL-LB" : "[U' : [R E' R' , U']]",
    "UL-FR" : "[U , L' E2' L]",
    "UL-FD" : "[l' : [U L U' , M]]",
    "UL-FL" : "[E : [U , L E' L']]",
    "UL-RU" : "[S , R' F R]",
    "UL-RB" : "[U , L' E L]",
    "UL-RD" : "[U' : [R E R' , U']]",
    "UL-RF" : "[U , L E' L']",
    "UL-BU" : "[L' : [M , U L U']]",
    "UL-BL" : "[u : [L' E L , U']]",
    "UL-BD" : "(U' M U' M') * 2",
    "UL-BR" : "[U , L E2' L']",
    "UL-DF" : "[R' F' : [R S R' , F2]]",
    "UL-DR" : "U R U R' U' R' U' R' U R",
    "UL-DB" : "D' U R U R' U' R' U' R' U R D",
    "UL-DL" : "[L U' L : [S' , L2']]",
    "LU-UB" : "[U M' U : [M , U2']]",
    "LU-UR" : "[L F' L' , S']",
    "LU-UL" : "",
    "LU-LU" : "",
    "LU-LF" : "[S : [U' , R' E R]]",
    "LU-LD" : "[l' U L' : [S' , L2]]",
    "LU-LB" : "[S : [U' , R E' R']]",
    "LU-FR" : "[M' : [U' , l E' l']]",
    "LU-FD" : "[l' : [M' , U' L U]]",
    "LU-FL" : "[r' F2 : [r S r' , F]]",
    "LU-RU" : "[M U : [M' , U2']]",
    "LU-RB" : "[L' F' : [E , L2]]",
    "LU-RD" : "[R' F R : [S , R2']]",
    "LU-RF" : "[R M U : [M' , U2]]",
    "LU-BU" : "[L' : [U' L U , M']]",
    "LU-BL" : "[U' R F : [R2' , E']]",
    "LU-BD" : "[M' : (U M' U M) * 2]",
    "LU-BR" : "[M' : [U' , L' E L]]",
    "LU-DF" : "[L' F' : [L2 , E']]",
    "LU-DR" : "[L : [F' , L S L']]",
    "LU-DB" : "[L' M : [U' L U , M2]]",
    "LU-DL" : "[L F' L' , S]]",
    "LF-UB" : "[U : [R' E R , U2]]",
    "LF-UR" : "[R' E R , U']",
    "LF-UL" : "[U2 : [R' E R , U]]",
    "LF-LU" : "[S : [R' E R , U']]",
    "LF-LF" : "",
    "LF-LD" : "[L , U S' U']",
    "LF-LB" : "[M' U L : [S' , L2']]",
    "LF-FR" : "[E , R U' R']",
    "LF-FD" : "[M2 : [U' L' U , M]]",
    "LF-FL" : "",
    "LF-RU" : "[M L' U : [M' , U2']]",
    "LF-RB" : "[r U R' : [E , R2]]",
    "LF-RD" : "[M' U R' : [E , R2]]",
    "LF-RF" : "[U E R' : [S , R2]]",
    "LF-BU" : "[U' L' U , M']",
    "LF-BL" : "[E' , L U L']",
    "LF-BD" : "[U' M : [U , R' E R]]",
    "LF-BR" : "[R2' : [E , R U' R']]",
    "LF-DF" : "[U R' F2 : [R S R' , F]]",
    "LF-DR" : "[U' E' R : [E' , R2']]",
    "LF-DB" : "[M : [U' L' U , M2]]",
    "LF-DL" : "[U E L : [E' , L2']]",
    "LD-UB" : "[U' : [L' E' L , U2']]",
    "LD-UR" : "[U2' : [L' E' L , U']]",
    "LD-UL" : "[L' E' L , U]",
    "LD-LU" : "[l' U L : [S' , L2']]",
    "LD-LF" : "[U S' U' , L]",
    "LD-LD" : "",
    "LD-LB" : "[U S U' , L']",
    "LD-FR" : "[L' E' : [L U L' , E']]",
    "LD-FD" : "[U : [L F L' , S]]",
    "LD-FL" : "[L f' L' : [S , L2]]",
    "LD-RU" : "[L F' L : [S' , L2']]",
    "LD-RB" : "[L F' : [E , L2']]",
    "LD-RD" : "[R' F R' : [S' , R2]]",
    "LD-RF" : "[M' U' L' : [E' , L2]]",
    "LD-BU" : "[L' : [U' L' U , M']]",
    "LD-BL" : "[S' U' R' : [E' , R2]]",
    "LD-BD" : "[U l : [L' U' L , E]]",
    "LD-BR" : "[D : [U' R' U , M']]",
    "LD-DF" : "[L F : [E' , L2']]",
    "LD-DR" : "[L' F' L , S]",
    "LD-DB" : "[U : [S' , L B' L']]",
    "LD-DL" : "",
    "LB-UB" : "[U : [R E' R' , U2]]",
    "LB-UR" : "[R E' R' , U']",
    "LB-UL" : "[U2 : [R E' R' , U]]",
    "LB-LU" : "[S : [R E' R' , U']]",
    "LB-LF" : "[E' R U' R' : [E' , R2]]",
    "LB-LD" : "[L' , U S' U']",
    "LB-LB" : "",
    "LB-FR" : "[R2 : [E' , R' U' R]]",
    "LB-FD" : "[U' M' : [U' , R E' R']]",
    "LB-FL" : "[E , L' U L]",
    "LB-RU" : "[R F : [R2' , E']]",
    "LB-RB" : "[u' L : [S' , L2']]",
    "LB-RD" : "[R' F : [R2 , E']]",
    "LB-RF" : "[E' R U' R : [E , R2']]",
    "LB-BU" : "[U' L U , M']",
    "LB-BL" : "",
    "LB-BD" : "[U' M : [U , r E' r']]",
    "LB-BR" : "[E' , R' U' R]",
    "LB-DF" : "[l' U : [S' , L2]]",
    "LB-DR" : "[u' R' : [E , R2]]",
    "LB-DB" : "[M : [U' L U , M2]]",
    "LB-DL" : "[u L' : [E , L2]]",
    "FR-UB" : "[R' U' : [R2' , S]]",
    "FR-UR" : "[E' : [R' E R , U']]",
    "FR-UL" : "[L' E2' L , U]",
    "FR-LU" : "[L : [E' , l' U' l]]",
    "FR-LF" : "[R U' R' , E]",
    "FR-LD" : "[D : [M' , U' R U]]",
    "FR-LB" : "[R : [U' , R E' R']]",
    "FR-FR" : "",
    "FR-FD" : "[M' , U' R U]",
    "FR-FL" : "[R' U' R : [E , R2']]",
    "FR-RU" : "[R' U' E' R : [E , R2']]",
    "FR-RB" : "[R U' R' , E']",
    "FR-RD" : "[R' f R' : [S' , R2]]",
    "FR-RF" : "",
    "FR-BU" : "[M , U' R U]",
    "FR-BL" : "[R' U' R' : [E' , R2]]",
    "FR-BD" : "[U L B' : [E' , L2']]",
    "FR-BR" : "[U R' : [S , R2]]",
    "FR-DF" : "[D' U L : [E' , L2']]",
    "FR-DR" : "U R' U' R' U R U R U R' U2",
    "FR-DB" : "[M2 ,  U' R U]",
    "FR-DL" : "[U L : [E' , L2']]",
    "FD-UB" : "[R' F' : [E , R U R']]",
    "FD-UR" : "[R : [U' R' U , M']]",
    "FD-UL" : "[L' : [U L U' , M']]",
    "FD-LU" : "[l' : [U' L U , M']]",
    "FD-LF" : "[M' : [U' L' U , M']]",
    "FD-LD" : "[l : [D' L' D , M']]",
    "FD-LB" : "[M' : [U' L U , M']]",
    "FD-FR" : "[U' R U , M']",
    "FD-FD" : "",
    "FD-FL" : "[U L' U' , M']",
    "FD-RU" : "[r : [U R' U' , M']]",
    "FD-RB" : "[M' : [U R' U' , M']]",
    "FD-RD" : "[r' : [D R D' , M']]",
    "FD-RF" : "[M' : [U R U' , M']]",
    "FD-BU" : "[U' : [S , R' F' R]]",
    "FD-BL" : "[U L U' , M']",
    "FD-BD" : "[U : [M' U' M , d2]]",
    "FD-BR" : "[U' R' U , M']",
    "FD-DF" : "",
    "FD-DR" : "[U R' F' R' : [S , R2]]",
    "FD-DB" : "[D : [R F R' , S']]",
    "FD-DL" : "[U' L F L : [S' , L2']]",
    "FL-UB" : "[L U : [L2' , S']]",
    "FL-UR" : "[R E2 R' , U']",
    "FL-UL" : "[E : [L E' L' , U]]",
    "FL-LU" : "[r' F' : [r S r' , F']]",
    "FL-LF" : "",
    "FL-LD" : "[L f' L : [S , L2']]",
    "FL-LB" : "[L' U L , E]",
    "FL-FR" : "[R' U' R' : [E , R2]]",
    "FL-FD" : "[M' , U L' U']",
    "FL-FL" : "",
    "FL-RU" : "[R' : [E , r U r']]",
    "FL-RB" : "[L' : [U , L' E L]]",
    "FL-RD" : "[U' : [S' , R' F2 R]]",
    "FL-RF" : "[L' U L , E']",
    "FL-BU" : "[M , U L' U']",
    "FL-BL" : "[U' L : [S' , L2']]",
    "FL-BD" : "[U' R' B : [E , R2]]",
    "FL-BR" : "[R U' R' : [E , R2]]",
    "FL-DF" : "[U' D R' : [E , R2]]",
    "FL-DR" : "[U' R' : [E , R2]]",
    "FL-DB" : "[M2 , U L' U']",
    "FL-DL" : "U' L U L U' L' U' L' U' L U2'",
    "RU-UB" : "[U' M' U' : [M , U2]]",
    "RU-UR" : "",
    "RU-UL" : "[R' F R , S]",
    "RU-LU" : "[M U' : [M' , U2]]",
    "RU-LF" : "[M L' U' : [M' , U2']]",
    "RU-LD" : "[L F' L' : [S' , L2]]",
    "RU-LB" : "[R F : [E' , R2']]",
    "RU-FR" : "[R' U' E' R' : [E , R2]]",
    "RU-FD" : "[r : [M' , U R' U']]",
    "RU-FL" : "[M' : [U , r' E r]]",
    "RU-RU" : "",
    "RU-RB" : "[S' : [U , L' E L]]",
    "RU-RD" : "[r U' R : [S , R2']]",
    "RU-RF" : "[S' : [U , L E' L']]",
    "RU-BU" : "[R : [U R' U' , M']]",
    "RU-BL" : "[M' : [U , R E' R']]",
    "RU-BD" : "[M' : (U' M' U' M) * 2]",
    "RU-BR" : "[R u' R : [E' , R2']]",
    "RU-DF" : "[R F : [R2' , E]]",
    "RU-DR" : "[R' F R , S']",
    "RU-DB" : "[R M : [U R' U' , M2]]",
    "RU-DL" : "[R' : [F , R' S' R]]",
    "RB-UB" : "[U' : [L' E L , U2']]",
    "RB-UR" : "[U2' : [L' E L , U']]",
    "RB-UL" : "[L' E L , U]",
    "RB-LU" : "[F R' : [S , R2]]",
    "RB-LF" : "[r U R : [E , R2']]",
    "RB-LD" : "[F R : [S' , R2']]",
    "RB-LB" : "[u R' : [S , R2]]",
    "RB-FR" : "[E' , R U' R']",
    "RB-FD" : "[M2 : [U R' U' , M]]",
    "RB-FL" : "[L2' : [E , L U' L']]",
    "RB-RU" : "[S' : [L' E L , U]]",
    "RB-RB" : "",
    "RB-RD" : "[R , U' S U]",
    "RB-RF" : "[E' R' U' R : [E , R2']]",
    "RB-BU" : "[U R' U' , M']",
    "RB-BL" : "[E , L U L']",
    "RB-BD" : "[U M : [U' , l' E l]]",
    "RB-BR" : "",
    "RB-DF" : "[r U' : [S , R2']]",
    "RB-DR" : "[u' R : [E' , R2']]",
    "RB-DB" : "[M : [U R' U' , M2]]",
    "RB-DL" : "[u L : [E' , L2']]",
    "RD-UB" : "[U : [R E R' , U2]]",
    "RD-UR" : "[R E R' , U']",
    "RD-UL" : "[U2 : [R E R' , U]]",
    "RD-LU" : "[R' F R' : [S , R2]]",
    "RD-LF" : "[M' U R : [E , R2']]",
    "RD-LD" : "[L F' L : [S , L2']]",
    "RD-LB" : "[R' F : [E' , R2]]",
    "RD-FR" : "[R' f R : [S' , R2']]",
    "RD-FD" : "[U' : [R' F' R , S']]",
    "RD-FL" : "[R E : [R' U' R , E]]",
    "RD-RU" : "[r U' R' : [S , R2]]",
    "RD-RB" : "[U' S U , R]",
    "RD-RD" : "",
    "RD-RF" : "[U' S U , R']",
    "RD-BU" : "[R : [U R U' , M']]",
    "RD-BL" : "[R' E' : [R U' R' , E']]",
    "RD-BD" : "[U' r' : [R U R' , E']]",
    "RD-BR" : "[S U L : [E , L2']]",
    "RD-DF" : "[R' F' : [E , R2]]",
    "RD-DR" : "",
    "RD-DB" : "[U' : [S , R' B R]]",
    "RD-DL" : "[R F R' , S']]",
    "RF-UB" : "[U' : [L E' L' , U2']]",
    "RF-UR" : "[U2' : [L E' L' , U']]",
    "RF-UL" : "[L E' L' , U]",
    "RF-LU" : "[R M U' : [M' , U2]]",
    "RF-LF" : "[U' E' L : [S' , L2']]",
    "RF-LD" : "[M' U' L : [E' , L2']]",
    "RF-LB" : "[E' R U' R' : [E , R2]]",
    "RF-FR" : "",
    "RF-FD" : "[M2 : [U R U' , M]]",
    "RF-FL" : "[E' , L' U L]",
    "RF-RU" : "[S' : [L E' L' , U]]",
    "RF-RB" : "[M' U' R' : [S , R2]]",
    "RF-RD" : "[R' , U' S U]",
    "RF-RF" : "",
    "RF-BU" : "[U R U' , M']",
    "RF-BL" : "[L2 : [E' , L' U L]]",
    "RF-BD" : "[U M : [U' , L E' L']]",
    "RF-BR" : "[E , R' U' R]",
    "RF-DF" : "[R2' F' : [E , R2]]",
    "RF-DR" : "[U' E' R' : [E , R2]]",
    "RF-DB" : "[M : [U R U' , M2]]",
    "RF-DL" : "[U E L' : [E , L2]]",
    "BU-UB" : "",
    "BU-UR" : "[R : [U' R' U , M]]",
    "BU-UL" : "[L' : [U L U' , M]]",
    "BU-LU" : "[l' : [U' L U , M]]",
    "BU-LF" : "[M' , U' L' U]",
    "BU-LD" : "[l' : [U' L' U , M]]",
    "BU-LB" : "[M' , U' L U]",
    "BU-FR" : "[U' R U , M]",
    "BU-FD" : "[U' : [R' F' R , S]",
    "BU-FL" : "[U L' U' , M]",
    "BU-RU" : "[r : [U R' U' , M]]",
    "BU-RB" : "[M' , U R' U']",
    "BU-RD" : "[r : [U R U' , M]]",
    "BU-RF" : "[M' , U R U']",
    "BU-BU" : "",
    "BU-BL" : "[U L U' , M]",
    "BU-BD" : "[U' : [R B R' , S]]",
    "BU-BR" : "[U' R' U , M]",
    "BU-DF" : "[U : [S , R' F' R]]",
    "BU-DR" : "[R' : [U' R' U , M]]",
    "BU-DB" : "[U : [S , R B R']]",
    "BU-DL" : "[L : [U L U' , M]]",
    "BL-UB" : "[L' U : [L2 , S']]",
    "BL-UR" : "[R' E2 R , U']",
    "BL-UL" : "[E' : [L' E L , U]]",
    "BL-LU" : "[U' R F : [E' , R2']]",
    "BL-LF" : "[L U L' , E']",
    "BL-LD" : "[S' U' R : [E' , R2']]",
    "BL-LB" : "",
    "BL-FR" : "[R' U' R : [E' , R2']]",
    "BL-FD" : "[M' , U L U']",
    "BL-FL" : "[U' L' : [S' , L2]]",
    "BL-RU" : "[r : [E' , R' U R]]",
    "BL-RB" : "[L U L' , E]",
    "BL-RD" : "[R' E2 : [R U' R' , E]]",
    "BL-RF" : "[L : [U , L E' L']]",
    "BL-BU" : "[M , U L U']",
    "BL-BL" : "",
    "BL-BD" : "[U2' : [M , U' L U]]",
    "BL-BR" : "[R U' R : [E' , R2']]",
    "BL-DF" : "[D U' R : [E' , R2']]",
    "BL-DR" : "[U' R : [E' , R2']]",
    "BL-DB" : "[U' D' R : [E' , R2']]",
    "BL-DL" : "U' L' U' L' U L U L U L'",
    "BD-UB" : "[U R' B R : [S , R2']]",
    "BD-UR" : "(M U' M' U') * 2",
    "BD-UL" : "(M U M' U) * 2",
    "BD-LU" : "[M2 : (U' M U' M') * 2]",
    "BD-LF" : "[U' r' : [E , R U R']]",
    "BD-LD" : "[U l : [E , L' U' L]]",
    "BD-LB" : "[U' M : [r E' r' , U]]",
    "BD-FR" : "[U L B' : [L2' , E']]",
    "BD-FD" : "[U : [M U M' , d2]]",
    "BD-FL" : "[U' R' B : [R2 , E]]",
    "BD-RU" : "[M2 : (U M U M') * 2]",
    "BD-RB" : "[U M : [l' E l , U']]",
    "BD-RD" : "[U' r' : [E' , R U R']]",
    "BD-RF" : "[U l : [E' , L' U' L]]",
    "BD-BU" : "[U' : [S , R B R']]",
    "BD-BL" : "[U : [L , U M U']]",
    "BD-BD" : "",
    "BD-BR" : "[U' : [R' , U' M U]]",
    "BD-DF" : "[D' : [R F R' , S']]",
    "BD-DR" : "[U L B' L' : [S , L2]]",
    "BD-DB" : "",
    "BD-DL" : "[U' R' B R : [S' , R2']]",
    "BR-UB" : "[R U' : [R2' , S]]",
    "BR-UR" : "[E : [R E' R' , U']]",
    "BR-UL" : "[L E2' L' , U]",
    "BR-LU" : "[l' : [E , L U' L']]",
    "BR-LF" : "[R' : [U' , R' E R]]",
    "BR-LD" : "[L E2' : [L' U L , E']]",
    "BR-LB" : "[R' U' R , E']",
    "BR-FR" : "[U R : [S , R2']]",
    "BR-FD" : "[M' , U' R' U]",
    "BR-FL" : "[R U' R : [E , R2']]",
    "BR-RU" : "[R u' R' : [E' , R2]]",
    "BR-RB" : "",
    "BR-RD" : "[D' : [M' , U' R' U]]",
    "BR-RF" : "[R' U' R , E]",
    "BR-BU" : "[M , U' R' U]",
    "BR-BL" : "[R U' R' : [E' , R2]]",
    "BR-BD" : "[U2 : [M , U R' U']]",
    "BR-BR" : "",
    "BR-DF" : "[U D' L' : [E , L2]]",
    "BR-DR" : "U R U R U' R' U' R' U' R",
    "BR-DB" : "[M2 , U' R' U]",
    "BR-DL" : "[U L' : [E , L2]]",
    "DF-UB" : "[M' , U2]",
    "DF-UR" : "[L F' : [L' S' L , F2']]",
    "DF-UL" : "[R' F : [R S R' , F2]]",
    "DF-LU" : "[L' F' : [E' , L2]]",
    "DF-LF" : "[U R' F' : [R S R' , F']]",
    "DF-LD" : "[L F : [L2' , E']]",
    "DF-LB" : "[l' U : [L2 , S']]",
    "DF-FR" : "[U R U' : [M' , U2]]",
    "DF-FD" : "",
    "DF-FL" : "[U' L' U : [M' , U2']]",
    "DF-RU" : "[R F : [E , R2']]",
    "DF-RB" : "[r U' : [R2' , S]]",
    "DF-RD" : "[R' F' : [R2 , E]]",
    "DF-RF" : "[R2' F' : [R2 , E]]",
    "DF-BU" : "[U : [R' F' R , S]",
    "DF-BL" : "[U' L U : [M' , U2']]",
    "DF-BD" : "[D' : [S' , R F R']]",
    "DF-BR" : "[U R' U' : [M' , U2]]",
    "DF-DF" : "",
    "DF-DR" : "[R' F : [R S' R' , F2]]",
    "DF-DB" : "[D2 , M]",
    "DF-DL" : "[L F' : [L' S L , F2']]",
    "DR-UB" : "[U' : [R2' , S]]",
    "DR-UR" : "[R U R' : [S , R2]]",
    "DR-UL" : "R' U' R U R U R U R U' R' U'",
    "DR-LU" : "[L2 : [S , L' F' L]]",
    "DR-LF" : "[U' E' R' : [E' , R2]]",
    "DR-LD" : "[S , L' F' L]",
    "DR-LB" : "[u' R : [E , R2']]",
    "DR-FR" : "U2 R U' R' U' R' U' R U R U'",
    "DR-FD" : "[U R' F' R : [S , R2']]",
    "DR-FL" : "[U' R : [E , R2']]",
    "DR-RU" : "[S' , R' F R]",
    "DR-RB" : "[u' R' : [E' , R2]]",
    "DR-RD" : "",
    "DR-RF" : "[U' E' R : [E , R2']]",
    "DR-BU" : "[r' : [U' R' U , M']]",
    "DR-BL" : "[U' R' : [E' , R2]]",
    "DR-BD" : "[U L B' L : [S , L2']]",
    "DR-BR" : "R' U R U R U R' U' R' U'",
    "DR-DF" : "[R' F' : [R S' R' , F2]]",
    "DR-DR" : "",
    "DR-DB" : "[U' R D R' : [S' , R2]]",
    "DR-DL" : "[U : [L2' , S]]",
    "DB-UB" : "[U2 , M]",
    "DB-UR" : "[R : [U' R' U , M2]]",
    "DB-UL" : "D' R' U' R U R U R U' R' U' D",
    "DB-LU" : "[l' : [U' L U , M2]]",
    "DB-LF" : "[M' : [U' L' U , M2]]",
    "DB-LD" : "[U : [L B' L' , S']]",
    "DB-LB" : "[M' : [U' L U , M2]]",
    "DB-FR" : "[U' R U , M2]",
    "DB-FD" : "[D : [S' , R F R']]",
    "DB-FL" : "[U L' U' , M2]]",
    "DB-RU" : "[r : [U R' U' , M2]]",
    "DB-RB" : "[M' : [U R' U' , M2]]",
    "DB-RD" : "[U' : [R' B R , S]]",
    "DB-RF" : "[M' : [U R U' , M2]]",
    "DB-BU" : "[U : [R B R' , S]]",
    "DB-BL" : "[U L U' , M2]",
    "DB-BD" : "",
    "DB-BR" : "[U' R' U , M2]",
    "DB-DF" : "[M' : [U2 , M']]",
    "DB-DR" : "[U' R' D R' : [S' , R2]]",
    "DB-DB" : "",
    "DB-DL" : "U' D R D R' D' R' D' R' D R U",
    "DL-UB" : "[U : [L2 , S']]",
    "DL-UR" : "L U L' U' L' U' L' U L U",
    "DL-UL" : "[L' U' L : [S' , L2']]",
    "DL-LU" : "[S , L F' L']",
    "DL-LF" : "[U E L' : [E' , L2]]",
    "DL-LD" : "",
    "DL-LB" : "[u L : [E , L2']]",
    "DL-FR" : "[U L' : [E' , L2]]",
    "DL-FD" : "[U' L F L' : [S' , L2]]",
    "DL-FL" : "U2' L' U L U L U L' U' L' U",
    "DL-RU" : "[R2' : [S' , R F R']]",
    "DL-RB" : "[u L' : [E' , L2]]",
    "DL-RD" : "[S' , R F R']",
    "DL-RF" : "[U E L : [E , L2']]",
    "DL-BU" : "[l : [U L U' , M']]",
    "DL-BL" : "L U' L' U' L' U' L U L U",
    "DL-BD" : "[U' R' B R' : [S' , R2]]",
    "DL-BR" : "[U L : [E , L2']]",
    "DL-DF" : "[L F : [L' S L , F2']]",
    "DL-DR" : "[U' : [R2' , S']]",
    "DL-DB" : "U' R' D' R D R D R D' R' U D'",
    "DL-DL" : ""
}
const flippedComms = {
    "BLLB" : "LBUR URBL",
    "BRRB" : "R' [URRU alg]",
    "DBBD" : "U2 M [UBBU alg]",
    "DFFD" : "M2 U2 M U R' F' R S R' F R S' U M",
    "DLLD" : "Mirror DRRD",
    "DRRD" : "S' R' F R U' M' U2 M U' S R' F' R",
    "FLLF" : "LFUR URFL",
    "FRRF" : "R [URRU alg]",
    "UBBU" : "U' S R' F' R S' R' F R U' M' U2 M",
    "ULLU" : "U' [URRU alg]",
    "URRU" : "R' E2 R2 E' R' U' R E R2 E2 R U"
};
const flippedComms3style = {
    "UB" : "M U' M U' M U2' M' U' M' U' M' U2'",
    "UR" : "Rw U R' U' Rw' U2' R U R U' R2' U2' R",
    "UL" : "[U': Rw U R' U' Rw' U2' R U R U' R2' U2' R]",
    "FL" : "[L' U': Rw U R' U' Rw' U2' R U R U' R2' U2' R]",
    "FR" : "[R: Rw U R' U' Rw' U2' R U R U' R2' U2' R]",
    "BL" : "[L U': Rw U R' U' Rw' U2' R U R U' R2' U2' R]",
    "BR" : "[R': Rw U R' U' Rw' U2' R U R U' R2' U2' R]",
    "DF" : "[D R2: Rw U R' U' Rw' U2' R U R U' R2' U2' R]",
    "DL" : "[L2 U': Rw U R' U' Rw' U2' R U R U' R2' U2' R]",
    "DR" : "[R2: Rw U R' U' Rw' U2' R U R U' R2' U2' R]",
    "DB" : "[D' R2: Rw U R' U' Rw' U2' R U R U' R2' U2' R]",
};
const flippedCommsM2 = {
    "UB" : "[F2: M U' M U' M U2' M' U' M' U' M' U2']",
    "UR" : "[M': Rw U R' U' Rw' U2' R U R U' R2' U2' R]",
    "UF" : "[M': M U' M U' M U2' M' U' M' U' M' U2']",
    "UL" : "[M' U': Rw U R' U' Rw' U2' R U R U' R2' U2' R]",
    "FL" : "[Lw' U': Rw U R' U' Rw' U2' R U R U' R2' U2' R]",
    "FR" : "[Rw: Rw U R' U' Rw' U2' R U R U' R2' U2' R]",
    "BL" : "[L M' U': Rw U R' U' Rw' U2' R U R U' R2' U2' R]",
    "BR" : "[R' M': Rw U R' U' Rw' U2' R U R U' R2' U2' R]",
    "DL" : "[L2 M' U': Rw U R' U' Rw' U2' R U R U' R2' U2' R]",
    "DR" : "[R2 M': Rw U R' U' Rw' U2' R U R U' R2' U2' R]",
    "DB" : "[M2: M U' M U' M U2' M' U' M' U' M' U2']",
};
const twistedComms3style = {
    "BDL" : "(R U' R' U) (R D' R' U') (R U R' U') (R D R' U)",
    "BDR" : "U (R U' R' D') (R U R' U') (R U R' D) (R U' R')",
    "BUL" : "[U2, R' D R D' R' D R]",
    "BUR" : "[R' D R D' R' D R, U]",
    "FDL" : "(R' D R U) (R' U' R U) (R' D' R U') (R' U R U')",
    "FDR" : "U (R' U' R U) (R' D' R U') (R' U R U') (R' D R)",
    "FUL" : "[R' D R D' R' D R, U']",
    "LDF" : "U (R' U' R U) (R' D R U') (R' U R U') (R' D' R)",
    "LFB" : "U' (R D' R' U) (R U' R' U) (R D R' U') (R U R')",
    "LUB" : "[R' D R D' R' D R, U2]",
    "LUF" : "[U', R' D R D' R' D R]",
    "RDB" : "(R U R' D') (R U' R' U) (R U' R' D) (R U R' U')",
    "RDF" : "(R' D' R U) (R' U' R U) (R' D R U') (R' U R U')",
    "RUB" : "[U, R' D R D' R' D R]"
};
const twistedCommsOP = {
    "BDL" : "[D F': R U R' U R U2 R' L' U' L U' L' U2 L]",
    "BDR" : "[R2 F': L' U2 L U L' U L R U2 R' U' R U' R']",
    "BUR" : "[R' F': R U R' U R U2 R' L' U' L U' L' U2 L]",
    "FDL" : "[F: L' U2 L U L' U L R U2 R' U' R U' R']",
    "FDR" : "[F2: R U R' U R U2 R' L' U' L U' L' U2 L]",
    "FUL" : "R U R' U R U2 R' L' U' L U' L' U2 L",//ccw
    "FUR" : "[F': L' U2 L U L' U L R U2 R' U' R U' R']",
    "LDF" : "[F: R U R' U R U2 R' L' U' L U' L' U2 L]",
    "LDB" : "[D F: L' U2 L U L' U L R U2 R' U' R U' R']",
    "LUF" : "L' U2 L U L' U L R U2 R' U' R U' R'",//cw
    "RDB" : "[R2 F': R U R' U R U2 R' L' U' L U' L' U2 L]",
    "RDF" : "[F2: L' U2 L U L' U L R U2 R' U' R U' R']",
    "RUF" : "[F': R U R' U R U2 R' L' U' L U' L' U2 L]",
    "RUB" : "[R' F': L' U2 L U L' U L R U2 R' U' R U' R']"
};
const m2 = {
    "BD" : "M2 D U R2 U' M' U R2 U' M D'",
    "BL" : "[U' L U: M2]",
    "BR" : "[U R' U': M2]",
    "BU" : "[B' R B U R2 U': M2]",
    "DB" : "M U2 M U2",
    "DL" : "[U' L2 U: M2]",
    "DR" : "[U R2 U': M2]",
    "FL" : "[U' L' U: M2]",
    "FR" : "[U R U': M2]",
    "FU" : "D M' U R2 U' M U R2 U' D' M2",
    "LB" : "[Uw' L' Uw: M2]",
    "LD" : "[B L B': M2]",
    "LF" : "[B L2 B': M2]",
    "LU" : "[B L' B': M2]",
    "RB" : "[Uw R Uw': M2]",
    "RD" : "[B' R' B: M2]",
    "RF" : "[B' R2 B: M2]",
    "RU" : "[B' R B: M2]",
    "UB" : "M2",
    "UF" : "U2 M' U2 M'",
    "UL" : "[L U' L' U: M2]",
    "UR" : "[R' U R U': M2]",
    "Parity" : "[D' L2 D: M2]"
};
const op = {
    "BDL" : "[D' R: R U' R' U' R U R' F' R U R' U' R' F R]",
    "BDR" : "[D': R U' R' U' R U R' F' R U R' U' R' F R]",
    "BUR" : "[R' F: R U' R' U' R U R' F' R U R' U' R' F R]",
    "DBL" : "[D F': R U' R' U' R U R' F' R U R' U' R' F R]",
    "DBR" : "[R2 F: R U' R' U' R U R' F' R U R' U' R' F R]",
    "DFL" : "[F': R U' R' U' R U R' F' R U R' U' R' F R]",
    "DFR" : "[D' F': R U' R' U' R U R' F' R U R' U' R' F R]",
    "FDL" : "[D: R U' R' U' R U R' F' R U R' U' R' F R]",
    "FDR" : "[F D: R U' R' U' R U R' F' R U R' U' R' F R]",
    "FUL" : "[F' D: R U' R' U' R U R' F' R U R' U' R' F R]",
    "FUR" : "[F2 D: R U' R' U' R U R' F' R U R' U' R' F R]",
    "LDB" : "[D2: R U' R' U' R U R' F' R U R' U' R' F R]",
    "LDF" : "[D2 R: R U' R' U' R U R' F' R U R' U' R' F R]",
    "LUF" : "[F2: R U' R' U' R U R' F' R U R' U' R' F R]",
    "RDB" : "[R: R U' R' U' R U R' F' R U R' U' R' F R]",
    "RDF" : "R U' R' U' R U R' F' R U R' U' R' F R",
    "RUB" : "[R2: R U' R' U' R U R' F' R U R' U' R' F R]",
    "RUF" : "[R': R U' R' U' R U R' F' R U R' U' R' F R]",
    "UBR" : "[R D': R U' R' U' R U R' F' R U R' U' R' F R]",
    "UFL" : "[F R': R U' R' U' R U R' F' R U R' U' R' F R]",
    "UFR" : "[F: R U' R' U' R U R' F' R U R' U' R' F R]"
};

const jperm = "R U R' F' R U R' U' R' F R2 U' R' U'";