const optimalSolutions = [
    "R'",
    "R",
    "r'",
    "r",
    "r' R'",
    "r R'",
    "r' R",
    "r R",
    "R' r'",
    "R r'",
    "R' r",
    "R r",
    "R' r' R'",
    "R r' R'",
    "R' r R'",
    "R r R'",
    "R' r' R",
    "R r' R",
    "R' r R",
    "R r R",
    "r' R' r'",
    "r R' r'",
    "r' R r'",
    "r R r'",
    "r' R' r",
    "r R' r",
    "r' R r",
    "r R r",
    "r' R' r' R'",
    "r R' r' R'",
    "r' R r' R'",
    "r R r' R'",
    "r' R' r R'",
    "r R' r R'",
    "r' R r R'",
    "r R r R'",
    "r' R' r' R",
    "r R' r' R",
    "r' R r' R",
    "r R r' R",
    "r' R' r R",
    "r R' r R",
    "r' R r R",
    "r R r R",
    "R' r' R' r'",
    "R r' R' r'",
    "R' r R' r'",
    "R r R' r'",
    "R' r' R r'",
    "R r' R r'",
    "R' r R r'",
    "R r R r'",
    "R' r' R' r",
    "R r' R' r",
    "R' r R' r",
    "R r R' r",
    "R' r' R r",
    "R r' R r",
    "R' r R r",
    "R r R r",
    "R' r' R' r' R'",
    "R r' R' r' R'",
    "R' r R' r' R'",
    "R r R' r' R'",
    "R' r' R r' R'",
    "R r' R r' R'",
    "R' r R r' R'",
    "R r R r' R'",
    "R' r' R' r R'",
    "R r' R' r R'",
    "R' r R' r R'",
    "R r R' r R'",
    "R' r' R r R'",
    "R r' R r R'",
    "R' r R r R'",
    "R r R r R'",
    "R' r' R' r' R",
    "R r' R' r' R",
    "R' r R' r' R",
    "R r R' r' R",
    "R' r' R r' R",
    "R r' R r' R",
    "R' r R r' R",
    "R r R r' R",
    "R' r' R' r R",
    "R r' R' r R",
    "R' r R' r R",
    "R r R' r R",
    "R' r' R r R",
    "R r' R r R",
    "R' r R r R",
    "R r R r R",
    "r' R' r' R' r'",
    "r R' r' R' r'",
    "r' R r' R' r'",
    "r R r' R' r'",
    "r' R' r R' r'",
    "r R' r R' r'",
    "r' R r R' r'",
    "r R r R' r'",
    "r' R' r' R r'",
    "r R' r' R r'",
    "r' R r' R r'",
    "r R r' R r'",
    "r' R' r R r'",
    "r R' r R r'",
    "r' R r R r'",
    "r R r R r'",
    "r' R' r' R' r",
    "r R' r' R' r",
    "r' R r' R' r",
    "r R r' R' r",
    "r' R' r R' r",
    "r R' r R' r",
    "r' R r R' r",
    "r R r R' r",
    "r' R' r' R r",
    "r R' r' R r",
    "r' R r' R r",
    "r R r' R r",
    "r' R' r R r",
    "r R' r R r",
    "r' R r R r",
    "r R r R r",
    "r' R' r' R' r' R'",
    "r R' r' R' r' R'",
    "r' R r' R' r' R'",
    "r R r' R' r' R'",
    "r' R' r R' r' R'",
    "r R' r R' r' R'",
    "r' R r R' r' R'",
    "r R r R' r' R'",
    "r' R' r' R r' R'",
    "r R' r' R r' R'",
    "r' R r' R r' R'",
    "r R r' R r' R'",
    "r' R' r R r' R'",
    "r R' r R r' R'",
    "r' R r R r' R'",
    "r R r R r' R'",
    "r' R' r' R' r R'",
    "r R' r' R' r R'",
    "r' R r' R' r R'",
    "r R r' R' r R'",
    "r' R' r R' r R'",
    "r R' r R' r R'",
    "r' R r R' r R'",
    "r R r R' r R'",
    "r' R' r' R r R'",
    "r R' r' R r R'",
    "r' R r' R r R'",
    "r R r' R r R'",
    "r' R' r R r R'",
    "r R' r R r R'",
    "r' R r R r R'",
    "r R r R r R'",
    "r' R' r' R' r' R",
    "r R' r' R' r' R",
    "r' R r' R' r' R",
    "r R r' R' r' R",
    "r' R' r R' r' R",
    "r R' r R' r' R",
    "r' R r R' r' R",
    "r R r R' r' R",
    "r' R' r' R r' R",
    "r R' r' R r' R",
    "r' R r' R r' R",
    "r R r' R r' R",
    "r' R' r R r' R",
    "r R' r R r' R",
    "r' R r R r' R",
    "r R r R r' R",
    "r' R' r' R' r R",
    "r R' r' R' r R",
    "r' R r' R' r R",
    "r R r' R' r R",
    "b' R' r b' R b",
    "r R' r R' r R",
    "r' R r R' r R",
    "r R r R' r R",
    "r' R' r' R r R",
    "r R' r' R r R",
    "r' R r' R r R",
    "r R r' R r R",
    "r' R' r R r R",
    "r R' r R r R",
    "r' R r R r R",
    "r R r R r R",
    "R' r R' r' R' r'",
    "R r' R r' R' r'",
    "R' r R r' R' r'",
    "R r' R' r R' r'",
    "R' r R' r R' r'",
    "R r R' r R' r'",
    "R' r' R r R' r'",
    "R r' R r R' r'",
    "R' r R r R' r'",
    "R' r' R' r' R r'",
    "R' r R' r' R r'",
    "R r R' r' R r'",
    "R' r' R r' R r'",
    "R r' R r' R r'",
    "R' r R r' R r'",
    "R r R r' R r'",
    "R' r' R' r R r'",
    "R r' R' r R r'",
    "R' r R' r R r'",
    "R r R' r R r'",
    "R' r' R r R r'",
    "R' r R r R r'",
    "R r' R' r' R' r",
    "R r R' r' R' r",
    "R' r' R r' R' r",
    "R r' R r' R' r",
    "R' r R r' R' r",
    "R r R r' R' r",
    "R' r' R' r R' r",
    "R r' R' r R' r",
    "R' r R' r R' r",
    "R r R' r R' r",
    "R' r' R r R' r",
    "R r' R r R' r",
    "R r R r R' r",
    "R r' R' r' R r",
    "R' r R' r' R r",
    "R r R' r' R r",
    "b' R' b r' R b",
    "R r' R r' R r",
    "R' r R r' R r",
    "R r' R' r R r",
    "R' r R' r R r",
    "R r' R r R r",
    "R r' R r' R' r' R'",
    "R' r R' r R' r' R'",
    "r' b' R' b r' R b",
    "R' r' R r R' r' R'",
    "R r' R r R' r' R'",
    "R' r R' r' R r' R'",
    "R r R' r' R r' R'",
    "R' r' R r' R r' R'",
    "r' f R r f' R' f'",
    "R' f R r' f R' f'",
    "R f R r' f R' f'",
    "R' r' R' r R r' R'",
    "R r' R' r R r' R'",
    "R' r R' r R r' R'",
    "R r R' r R r' R'",
    "R' r' R r R r' R'",
    "R r' R' r' R' r R'",
    "R' r' R r' R' r R'",
    "R r' R r' R' r R'",
    "R' r R r' R' r R'",
    "R r R r' R' r R'",
    "R' r' R' r R' r R'",
    "R r' R' r R' r R'",
    "r' b' f r' f r' b",
    "R r R' r R' r R'",
    "R' r' R r R' r R'",
    "R r' R r R' r R'",
    "R r R r R' r R'",
    "R r' R' r' R r R'",
    "R' r R' r' R r R'",
    "R r R' r' R r R'",
    "b' R' b r' R b R'",
    "R r' R r' R r R'",
    "R' r R r' R r R'",
    "R r' R' r R r R'",
    "R r' R r R r R'",
    "R' r R' r R' r' R",
    "R r R' r R' r' R",
    "R' r' R r R' r' R",
    "R r' R r R' r' R",
    "R' r R' r' R r' R",
    "R r R' r' R r' R",
    "R' r' R r' R r' R",
    "r f b' r b' r f'",
    "R' r R r' R r' R",
    "R r R r' R r' R",
    "R' r' R' r R r' R",
    "R r' R' r R r' R",
    "R' r R' r R r' R",
    "R r R' r R r' R",
    "R' r' R r' R' r R",
    "R r' R r' R' r R",
    "R' r R r' R' r R",
    "R r R r' R' r R",
    "R' b' R' r b' R b",
    "R b' R' r b' R b",
    "r b' R' r' b R b",
    "R r R' r R' r R",
    "R' r' R r R' r R",
    "R r' R r R' r R",
    "R' r R' r' R r R",
    "R r R' r' R r R",
    "r f R f' r R' f'",
    "R r' R r' R r R",
    "r R' r R r' R' r'",
    "r R r' R' r R' r'",
    "R' f R f r' R' f'",
    "r' f R f' r R' f'",
    "r R' r' R r R' r'",
    "r' R r' R r R' r'",
    "r R r' R r R' r'",
    "r' R' r R r R' r'",
    "r R' r R' r' R r'",
    "r' R r R' r' R r'",
    "r R r R' r' R r'",
    "r R' r' R r' R r'",
    "R' b' r f' r f' b",
    "f R r f' R' f' R",
    "r' R' r R r' R r'",
    "r R' r R r' R r'",
    "r R' r' R' r R r'",
    "r' R r' R' r R r'",
    "r R r' R' r R r'",
    "b' R' r b' R b r'",
    "r R' r R' r R r'",
    "r' R r R' r R r'",
    "r R' r' R r R r'",
    "r' R r' R r' R' r",
    "r R r' R r' R' r",
    "r' R' r R r' R' r",
    "r R' r R r' R' r",
    "r' R r' R' r R' r",
    "r R r' R' r R' r",
    "b' R' r' b R b R'",
    "R f r' b r' b f'",
    "r' R r R' r R' r",
    "r' R' r' R r R' r",
    "r R' r' R r R' r",
    "r' R r' R r R' r",
    "r' R' r R' r' R r",
    "r R' r R' r' R r",
    "r' R r R' r' R r",
    "r b' R' b r' R b",
    "R b' R' b' r R b",
    "r' R' r R r' R r",
    "r' R r' R' r R r",
    "r' R r' R r R' r' R'",
    "R' r' R' r R r' R r",
    "f r' b R f' r b r",
    "R' r' R r' R' r R r",
    "r f R r f' R' f'",
    "f R r f' R' f'",
    "r' R' f R r' f R' f'",
    "R r b R' f' r' b' f",
    "b R' f' r' b' f R r'",
    "R' b' R' r' b R b r",
    "b' R' r b' R b r' R'",
    "R' b' R' r' b R b R",
    "b' r f' R' b r' f'",
    "f b r' R r f' b",
    "R f R r f' R' f'",
    "r' R f R r f' R' f'",
    "R' r b R' f' r' b' f",
    "r R' r R r' R' r R'",
    "b' R' r' b R b r",
    "r' b' R' r' b R b r",
    "r b' f r' f r' b",
    "b' f r' f r' b",
    "r R' r R' r R' r' R",
    "R b' r f' R' b r' f'",
    "r R' r' R r R' r R'",
    "f' b R b' f' b R b'",
    "r' R' r R' r' R r R'",
    "r R' r R' r' R r R'",
    "R' f' b r f R b' r'",
    "r b' R' b r' R b R'",
    "R b' R' b' r R b R'",
    "b' f' r R' r' b f'",
    "f r' b R f' r b",
    "r' R r' R r R' r' R",
    "R' b' f' r R' r' b f'",
    "r' R r R' r' R r' R",
    "r R r R' r' R r' R",
    "f b' r b' r f'",
    "r' f b' r b' r f'",
    "f b' r b' r f' R r'",
    "f R r f' R' f' r'",
    "r' R r' R' r R r' R",
    "r R r' R' r R r' R",
    "r R' b' R' r' b R b",
    "R' b' R' r' b R b",
    "R r' f b' r b' r f'",
    "r R r' R r' R' r R",
    "r' R' r R r' R' r R",
    "f' R b r f b' R' r",
    "r' R b' R' r b' R b",
    "r R b' R' r b' R b",
    "b' R' r' b R b",
    "r' b' R' r' b R b",
    "R r R' r R r' R' r'",
    "r R' r' R r R' r R",
    "R r R r' R' r R' r'",
    "f b r' R r f' b r'",
    "R' r R' r R r' R' r'",
    "f b' r R r' f b R",
    "R f R f r' R' f'",
    "f R f r' R' f'",
    "R' r' f R f' r R' f'",
    "R r' f R f' r R' f'",
    "R' r R' r' R r R' r'",
    "r' b' R' b' r R b R",
    "b' R' b r' R b R' r'",
    "r' b' R' b' r R b r",
    "b' f r' R' r b' f'",
    "f r b' R f r' b",
    "r f R f r' R' f'",
    "R' r f R f r' R' f'",
    "r' R b f' r' b' R' f",
    "R r' R r R' r' R r'",
    "b' R' b' r R b R",
    "R' b' R' b' r R b R",
    "R b' r f' r f' b",
    "b' r f' r f' b",
    "R r' R r' R r' R' r",
    "r b' f r' R' r b' f'",
    "R r' R' r R r' R r'",
    "b' r' f b f r b' f'",
    "R' r' R r' R' r R r'",
    "R r' R r' R' r R r'",
    "b R' b' f b R' b' f",
    "R b' R' r b' R b r'",
    "R b' R' r' b R b R'",
    "b' r' f R' b' r f'",
    "f b' r R r' f b",
    "R' r R' r R r' R' r",
    "R r R' r R r' R' r",
    "R' r R r' R' r R' r",
    "R r R r' R' r R' r",
    "f r' b r' b f'",
    "R' f r' b r' b f'",
    "R' r' R r R' r R' r",
    "f R f r' R' f' R'",
    "R' r R' r' R r R' r",
    "R r R' r' R r R' r",
    "b' R' b r' R b R' r",
    "r' b' R' b' r R b",
    "r R' f r' b r' b f'",
    "R r R' r R' r' R r",
    "R' r' R r R' r' R r",
    "R r' R r R' r' R r",
    "r' R' f' b r f R b'",
    "R r b' R' b r' R b",
    "b' R' b' r R b",
    "R' b' R' b' r R b",
    "R r' R' r R r' R r",
    "f r b' R f r' b R'",
    "f r f b f' R' f' b f",
    "r' R b' r f' r f' b R'",
    "f' R' b f r R' f' b' f'",
    "b' r' f r f r' f' b r'",
    "b' f' r b f r b' f'",
    "b' r f' r f' b R'",
    "R' f R r f' R' f'",
    "f b' r R f r f' r' b",
    "r' f' R b r f b' r",
    "r b R' f' r' b' f",
    "b' f' b' R' r b f R' b'",
    "r' R' b R' f' r' b' f",
    "r' f' R b r f b' R",
    "R' r' R f R r f' R' f'",
    "R b' R' r' b R b R",
    "R' b' r f' R' b r' f'",
    "f b' r R r' f b R'",
    "r f r b' r b' f' R' r'",
    "r b' f r f' r' f' r b",
    "b' R r' b R' b R b",
    "R' f r' b r' b f' R r",
    "R' b' f r' f r' b",
    "R b' f r' f r' b",
    "r' R' b r R r' R b",
    "f R f r' R' f' R",
    "b f R r' R' b f' R' b'",
    "b r R r' R b R r'",
    "b f' r' b' R' f r",
    "r' b' R' b' r R b R'",
    "r' b' R' b R' r' b' r",
    "r' b f' r' b' R' f r",
    "R f' b r f R b' r'",
    "f' b r f R b' r'",
    "b r b R f' R f b r'",
    "r' f' r' R' r R' f' R' r",
    "b' R' b' r R b R'",
    "R' b' R' b' r R b R'",
    "R b' f' r R' r' b f'",
    "f r b' R f r' b R",
    "r f' b r f R b' r'",
    "b' r f b' R' f' b' f",
    "b f' r' b' R' f R' r'",
    "R' f' r' R' r R' f' R' r",
    "R' f b' r b' r f'",
    "R f b' r b' r f'",
    "b' R' r R' r' b' R r",
    "R f R' r f' R f' R' f'",
    "r' b r R b' R b r",
    "R' f R r f' R' f' r'",
    "r R f r' b R f' r b",
    "r' R' b R' f' r' b' f R'",
    "r' f' R b r f b'",
    "R' f R r' f R' f' r R",
    "R b' R' r' b R b",
    "r' R f R r' R r f",
    "f b' r' b r R f r' b",
    "r b R' f' r' b' f r'",
    "f' b' f R f b' f' r' f'",
    "f r' b r' b f' R",
    "R b' f r' f r' b R'",
    "b' r' f R' b' r f' R' r'",
    "b R f' b' r' R b f b",
    "R' f b r' R r f' b r'",
    "R f b r' R r f' b r'",
    "b' r f' R' b r' f' r R",
    "r f b' r R r' f b R",
    "r b' f r' f r' b r'",
    "b' f r' f r' b r'",
    "r' f R f r' R' f'",
    "R' f' b r f R b' R",
    "R b f' r' b' R' f",
    "R' r' b f' r' b' R' f",
    "R' f' b r f R b' r",
    "r' f R f' r R' f' R r'",
    "r b' R' b' r R b r",
    "r' b' f r' R' r b' f'",
    "f r' b R f' r b r'",
    "R' f R r' f r f' R' f'",
    "R' b' f' r R' r' b f' r'",
    "b' R r' b R' r R b",
    "r' f b' r b' r f' r R",
    "r' b' r f' r f' b",
    "r b' r f' r f' b",
    "R' r' b r R b' R b",
    "f R r f' R' f' r",
    "R' r' b' r' f r' f b R",
    "b r R b' R b r R'",
    "b R' f' r' b' f R",
    "R' b' R' r' b R b r'",
    "R' b' R' r R' r' b' R",
    "R' b R' f' r' b' f R",
    "r f' R b r f b' R'",
    "f' R b r f b' R'",
    "R' r' f' R b r f b' r'",
    "R' f' r' R' f R' f' r' R",
    "b' R' r' b R b r'",
    "r' b' R' r' b R b r'",
    "r b' r' f R' b' r f'",
    "f b r' R r f' b r",
    "R f' R b r f b' R'",
    "R' r' f r' b r' b f'",
    "b R' f' r' b' f r' R'",
    "r' f' r' R' f R' f' r' R",
    "r' f r' b r' b f'",
    "r f r' b r' b f'",
    "r' R' f r' b r' b f'",
    "r' f r' b r' b f' r R'",
    "b R' r' b' f' r b f'",
    "r' f R f r' R' f' R'",
    "R f b r' R r f' b r",
    "R b' R' r b' r' b R b",
    "R' f' b r f R b'",
    "r' f R f' r R' f' R r",
    "r b' R' b' r R b",
    "R r f' b r f R b'",
    "R b f' r' b' R' f R'",
    "f b' r b' r f' r",
    "r b' r f' r f' b r'",
    "b' f' r R' r' b f' r' R'",
    "R r b' r f' r f' b r'",
    "f R f' R r f r' R",
    "R f b r' b r' f' r' R",
    "f' r b r f' R b' f' b' R",
    "r' b' r f' r f' b R'",
    "R b' R' r R' r' b'",
    "r' R' f R r f' R' f'",
    "f' R' f R b R b' r'",
    "r f' R b r f b' r",
    "f' R b r f b' r",
    "b R' f' r' b' f",
    "r' b R' f' r' b' f",
    "R' b' R' r R' r' b'",
    "R' b R' f' r' b' f",
    "r f' R b r f b' R",
    "f' R b r f b' R",
    "b R' r f r f b' f",
    "f' r' b' f' b R' r' f'",
    "R r' b R' f' r' b' f",
    "r' R' r' b' f' r f' r b",
    "b' f r f' r' f' r b",
    "b' f' r f r f' r' b",
    "R f' R b r f b' R",
    "f R f' r f r' R' f'",
    "f' r' R' f R' f' r'",
    "f R f r' f' r R' f'",
    "r' R' b' f r' f r' b",
    "r R' b' f r' f r' b",
    "b' R' b R' r' b' r",
    "r R' b r R r' R b",
    "R' b r R r' R b",
    "R' f' b' R' r R b f",
    "R b' f' r f r f' r' b",
    "R' b' f' r f' r b r",
    "R' f' b r f R b' R'",
    "R r b r R r' R b",
    "R b f r' f' R' b' f",
    "r' f' b r f R b' r'",
    "f R f' R r f R r",
    "R f' r' R' r R' f'",
    "r' R f' r' R' r R' f'",
    "f b r' b' r' b r f'",
    "f b' r' b r b r' f'",
    "f R f' R r f r'",
    "b r f' R' f b r' b'",
    "f' r' R' f' r' R' f' R' r",
    "r' b' r f' r f' b R",
    "R b' R' r R' r' b' R'",
    "b' r f' R' r b' f' R' r",
    "R r f b r' b r' f'",
    "r b r R b' R b r",
    "b r R b' R b r",
    "b R' f' r' b' f R'",
    "f' R' f R b R b' r",
    "R' b' R' r R' r' b' R'",
    "b' r' f r' f b R r",
    "r f' R b r f b'",
    "f' R b r f b'",
    "R' b' R' r R' r' b' r'",
    "f' R r' b' r' b' f b'",
    "b R r b' r' R' b' r",
    "f' r' R' f r f' R' f'",
    "R f' R b r f b'",
    "R f R r' R r f",
    "b R' f' r' b' f r'",
    "R r f r b' r b' f'",
    "R' f R r' R r f",
    "r' R' f R r' R r f",
    "b' R' b R' r' b' r R'",
    "R' r f r b' r b' f' R' r",
    "f r' b f r R f R' b",
    "f R r' R r f R' r",
    "r f r b' r b' f' R' r",
    "R b r R r' R b R'",
    "r b' R' b R' r' b'",
    "R' r' f R f r' R' f'",
    "f' b' r b R f b' R'",
    "R f' b r f R b' R",
    "f' b r f R b' R",
    "b f' r' b' R' f",
    "R' b f' r' b' R' f",
    "r' b' R' b R' r' b'",
    "r' b f' r' b' R' f",
    "b f R r' R' f' b' R'",
    "f' b r f R b' r",
    "r f' b r f R b' R",
    "f' r' f' R' b R' b' f'",
    "r R' b f' r' b' R' f",
    "b R' f' r b r f' r f",
    "b' r f r' f' r' f b",
    "b' r' f r f r' f' b",
    "r f' b r f R b' r",
    "f R r' f r f' R' f'",
    "f' r' R' r R' f' R'",
    "f R r f' r' f R' f'",
    "f' r' R' r R' f' R r",
    "b' r f' r f' b R r'",
    "b' R' r R' r' b' R",
    "R r' b r R b' R b",
    "r' b r R b' R b",
    "r' f' R' r' f r R f",
    "R r' b' r' f r' f b R",
    "r' b' r' f r' f b R",
    "r' f' R b r f b' r'",
    "r R b r R b' R b",
    "b f R r R' f' b' R'",
    "R' f' R b r f b' R'",
    "f R r' R r f r R",
    "r f' r' R' f R' f'",
    "R' r f' r' R' f R' f'",
    "f r b' r' b' r b f'",
    "f r' b' r b r b' f'",
    "f R r' R r f R'",
    "b r b' f' R f r' b'",
    "f' r b f r' R f' R' b'",
    "R' r f r' b r' b f'",
    "r b' R' b R' r' b' r'",
    "R f R f r' R' f' R r",
    "r R f r b' r b' f'",
    "R b r R r' R b R",
    "b r R r' R b R",
    "b f' r' b' R' f r'",
    "f' b' r b R f b' R",
    "r' b' R' b R' r' b' r'",
    "b' f' r f' r b r R",
    "R f' b r f R b'",
    "f' b r f R b'",
    "r' b' R' b R' r' b' R'",
    "f' b f' r' f' r' R b'",
    "b f R r' R' f' b' R",
    "f' r' R' r f r' R' f'",
    "r f' b r f R b'",
    "r f R f' R r f",
    "b f' r' b' R' f R'",
    "r R f b r' b r' f'",
    "r' f R f' R r f",
    "b' r f' r f' b R r",
    "b' R' r R' r' b' R r'",
    "b' r f r' f' r' f b R'",
    "r' R f b r' b r' f'",
    "R f R f' R r f r' R",
    "f b r' b r' f' r' R",
    "r f R f r R r f",
    "b r R r b R b r'",
    "R r' b' r f' r f' b R'",
    "b' R' r R' r' b'",
    "b' r' f r' f b R r'",
    "r' b r R b' R b R'",
    "f' b' R' r' R b f",
    "R r' b' r' f r' f b",
    "r' b' r' f r' f b",
    "R' f' R b r f b' r",
    "R b R' f' r' b' f",
    "r' b' f' r f' r b",
    "R' f' R b r f b' R",
    "f R r' R r f r",
    "r' b' r' f R' r' b f'",
    "b' R b' R' b' r b' r' b'",
    "R' b' f r f' r' f' r b",
    "R' b' f' r f r f' r' b",
    "f R r' R r f R",
    "r R b' f' r f' r b",
    "f' r' R' r' f' R' f' r'",
    "R' r R' b' f r' f r' b",
    "r R f' r' R' r' f' R' f'",
    "R' b' R' b R' r' b' r",
    "R b' R' b R' r' b' r",
    "R b r R r' R b",
    "b r R r' R b",
    "f r b' r b' f' r'",
    "f' b' R' r R b f",
    "R b' f' r f' r b r",
    "b' f' r f' r b r",
    "R f' b r f R b' R'",
    "f' b r f R b' R'",
    "r b r R r' R b",
    "b r R r b' r' R b",
    "b f r' f' R' b' f",
    "b' r' f r' f b r",
    "r f' b r f R b' R'",
    "r' f' r' R' r R' f'",
    "b f' r' b' R' f R",
    "b r R b' R b R' r",
    "f' r' R' r R' f'",
    "R' f' r' R' r R' f'",
    "b' r' f r f r' f' b R",
    "b' r f r' f' r' f b R",
    "R' f R f' R r f r'",
    "f b' r R f' r b r",
    "f b r' b r' f' r'",
    "b' r' f r' f b R' r'",
    "R' r' b' r f' r f' b R",
    "R r' b' r f' r f' b R",
    "b' R' r R' r' b' R'",
    "b' f' r R' b' r f' R r",
    "r' b r R b' R b R",
    "r f b r' b r' f'",
    "b r R r b R b r",
    "r' b' r' f r' f b R'",
    "b' R' r R' r' b' r'",
    "f' r' f r' b' r b' f",
    "b f R r R' f' b'",
    "R' f' R b r f b'",
    "f R r' f' r R r f",
    "r f' r' R' f R' f' R",
    "f r b' r b' f' R' r",
    "f R r' R r f",
    "r f r b' r b' f'",
    "R' r f r b' r b' f'",
    "r f r b' r b' f' R r'",
    "r b' R' b' r' R' r' b'",
    "f' r' f' r f' R' f' R f'",
    "r R' b' f' r f' r b",
    "r' b' R' b' r' R' r' b'",
    "b' f' r f' r b r R'",
    "b r f R' f r f R' b",
    "R f R r f R r f",
    "b r R b r R b R'",
    "r f r' b r' b f' R' r'",
    "b' R' b R' r' b'",
    "R' b r R r' R b r'",
    "b R' b' R' f' R f",
    "R' b' f' r f' r b",
    "r' f' b r f R b' R",
    "r b f' r' b' R' f",
    "R' b' r' f r' f b",
    "r' f' b r f R b' r",
    "f R f' R r f R",
    "R r' b' R' r R' r' b'",
    "b' R f' r' f' R f' r' b'",
    "r R r' b r R b' R b",
    "f R f r R r f r' R'",
    "f R f' R r f r",
    "R f b r' b r' f' r",
    "f' r' R' f' r' R' f' R'",
    "r' b' r f' r f' b R r'",
    "f' r' R' f' r' R' f' R r",
    "r' b' R' r R' r' b' R",
    "r b' R' r R' r' b' R",
    "r b r R b' R b",
    "b r R b' R b",
    "f b r' b r' f' R'",
    "f' R' r' f r R f",
    "r b' r' f r' f b R",
    "b' r' f r' f b R",
    "r f' R b r f b' r'",
    "f' R b r f b' r'",
    "R b r R b' R b",
    "r' R b r R b' R b",
    "b R b' R' f' R' f",
    "b' f' r f' r b R",
    "R f' R b r f b' r'",
    "R' f' r' R' f R' f'",
    "b R' f' r' b' f r",
    "b R' f R' b' f r' b'",
    "f' r' R' f R' f'",
    "r' f' r' R' f R' f'",
    "r' R' r f' r' R' f R' f'",
    "R r f' r' R' r' f' R' f'",
    "r' f R r' R r f R'",
    "f r' b R r' f b R",
    "f r b' r b' f' R'",
    "b' f' r f' r b r' R'",
    "r' f r' b r' b f' R' r",
    "r f r' b r' b f' R' r",
    "b' R' b R' r' b' r'",
    "R' r f' r' R' r' f' R' f'",
    "R' b r R r' R b r",
    "R f r b' r b' f'",
    "b r R b r R b R",
    "R' r' f r b' r b' f'",
    "b' R' b R' r' b' R'",
    "f' r' b f' R' b R' f",
    "f' R f R b R' b'",
    "r' f' b r f R b'",
    "f R f' R r f R r'",
    "R f' r' R' r R' f' r",
    "f R f' R r f",
    "R f b r' b r' f'",
    "R f b r' b r' f' r R'",
    "R b' R' r' b' R' r' b'",
    "b' r f' R' r b' f' R' r'",
    "R' b' R' r' b' R' r' b'",
    "R b' r f' R' r b' f'",
    "b R' f' b f' r f' b' f'",
    "f R f r R r f",
    "r b' r' f r' f b R' r",
    "b' r' f r' f b R' r",
    "r' b' R' r R' r' b'",
    "r b' R' r R' r' b'",
    "r b r R b' R b R'",
    "b r R b' R b R'",
    "R b' r' f r' f b",
    "f' R' f R b R b' R'",
    "r b' r' f r' f b",
    "b' r' f r' f b",
    "R r b' R' r R' r' b'",
    "f' b r f R b' R' r'",
    "r' R b R' f' r' b' f",
    "r R b R' f' r' b' f",
    "r b' f' r f' r b",
    "b' f' r f' r b",
    "f' r' R' f R' f' R r",
    "R b' R' b R' r' b'",
    "r b r R r' R b r'",
    "b r R r' R b r'",
    "R' b' R' b R' r' b'",
    "b' r' f R' r' b f'",
    "R' b r R b r R b",
    "b' R' b' r' R' r' b' r",
    "R b r R r' R b r'",
    "f r' b R r' f b",
    "R b' f' r f' r b",
    "b' f' r f' r b r' R",
    "R r' R b' f' r f' r b",
    "R r' f r b' r b' f' R r'",
    "b' R' b' r' R' r' b' R",
    "b' r' f R' r' b f' r",
    "r f' r' R' f R' f' R' r",
    "R' b' f' r f' r b R",
    "b r R b r R b",
    "r' b r R b r R b",
    "b' f b' r' f' b f'",
    "r' b' f' r f' r b r",
    "r b f r' f' R' b' f",
    "r' f' b r f R b' R'",
    "r b f' r' b' R' f R",
    "r' b' r' f r' f b r",
    "r f' r' R' r R' f'",
    "R' b' r' f r' f b R",
    "b' R' r' b' R' r' b' r",
    "f' r' R' f' r' R' f'",
    "f R f r R r f r'",
    "R f' r' R' f' r' R' f'",
    "r f r b' R r f' b r'",
    "f r b' R r f' b r'",
    "R' b r R r b R b",
    "R r' R f b' r b' r f' r'",
    "R' f b r' b r' f' r R'",
    "b' r f' R' r b' f'",
    "r' b' r f' R' r b' f'",
    "f r b' R r f' b",
    "R f R f' R r f",
    "f b r' b r' f'",
    "r' f b r' b r' f'",
    "r b' r' f r' f b R'",
    "R' f b r' b r' f'",
    "f' r' R' r R' f' r",
    "r b' R' r R' r' b' r'",
    "R' f R f' R r f",
    "b r R b' R b R' r'",
    "r R' f r b' r b' f'",
    "R' f r b' r b' f'",
    "R' r' f' b r f R b'",
    "R b' R' b R' r' b' R'",
    "b f' r' b' R' f R r",
    "b r R r' R b r' R'",
    "f' r' R' f R' f' R",
    "R b' R' b R' r' b' r'",
    "r' f R r' R r f",
    "r f R r' R r f",
    "f r b' r b' f'",
    "r' f r b' r b' f'",
    "R r' f r b' r b' f'",
    "r' f r b' r b' f' R r'",
    "b' R' b' r' R' r' b'",
    "b f' r' R b' r f' r' f'",
    "R' f r' b R r' f b",
    "r b' f r' R' b r' f'",
    "f R r f R r f",
    "b' f' r R' b' r f'",
    "r' b r R r b R b",
    "b' R' r' b' R' r' b' R",
    "f b' r R f' r b",
    "b' f' r R' b' r f' R",
    "b r R r b R b",
    "f' r' R' r' f' R' f'",
    "f R r f R r f R'",
    "r f' r' R' r' f' R' f'",
    "f b r' R f r' b R'",
    "b' f r' R' b r' f'",
    "f b r' R f r' b",
    "b' R' r' b' R' r' b'",
    "r' f b' r R f' r b",
    "R' b' r f' R' r b' f'",
    "f b' r R f' r b R'",
    "R b' r' f R' r' b f'",
    "b f r b f r b f",
    "f' r' R' r' f' R' f' R' r",
    "f b r' R f r' b R",
    "b' R' r' b' R' r' b' R'",
    "R' f r b' R r f' b r'",
    "r' b' f r' R' b r' f'",
    "f r' b R r' f b r'",
    "r' b' R' r' b' R' r' b'",
    "b R b f b f R f",
    "f' r' R' f' r' R' f' r' R",
    "b f R' b f R' b f",
    "b' R' b' r' R' r' b' r'",
    "R' f r' b R r' f b r'",
    "f' b' r' f' b' r' f' b' r'",
    "R' f r b' R r f' b r",
    "f' b' R f' b' R f' b' R",
    "R f r' b R r' f b r'"
]

function makeDrawings() {
    $("#scrambles").html("");
    let scrambles = $("#taScrambles").val().split("\n");

    let i = 0;
    
    for (let s of scrambles) {
        let ns = [];
        for (let m of s.split(" ")) {
            if (m.includes("R")) {
                ns.push("z " + m + " z'");
            }
            else if (m.includes("r")) {
                ns.push(m.toUpperCase());
            }
            else {
                ns.push(m);
            }
        }
        let el = "<br><div style='width: 100%; height: 20%; margin: auto; padding: 1%; display: grid; grid-template-columns: 2fr 3fr; border: 1px solid black;'><div><svg id='svgSkewb" + i + "'></svg></div><h1 style='margin: auto'>2gen: " + s + "<br>Optimal: " + optimalSolutions[i] + "</h1></div>";
        $("#svgSkewb" + i).attr("height", $("#svgSkewb" + i).attr("width") * 3 / 4);
        $("#svgSkewb" + i).css("height", $("#svgSkewb" + i).attr("height"));
        $("#svgSkewb" + i).css("margin", "auto");
        $("#scrambles").append(el);
        drawScrambleSkewb("#svgSkewb" + i, "x' " + inverseAlg(ns.join(" ")), true);
        i++;
    }

    $("#btnDownload").css("display", "block");
}

function makePDF() {
    // downloadPDF($("#content").html());

    let mywindow = window.open("", 'PRINT', 'height='+$(window).height()+'",width='+$(window).width());
    mywindow.document.write($("#content").html());
    mywindow.document.close();
    mywindow.focus();
    mywindow.print();
    // mywindow.close();
}

async function downloadPDF(el) {
    let fileName = "skvib.pdf";

    const link = document.createElement("a");
    link.href = URL.createObjectURL(el);
    link.download = fileName;
    link.target = "_blank";
    link.setAttribute("type", "hidden");

    document.body.appendChild(link);

    link.click();
    link.remove();
};

async function getBlob(toBlob) {
    let res = await fetch(`data:${toBlob};base64`);

    return await res.blob();
}